# Generated by Django 5.2.4 on 2025-08-13 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('employees', '0009_alter_employeedepartment_date_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('all_day', models.BooleanField(default=True, verbose_name='Весь день')),
                ('recurrence', models.CharField(choices=[('one_time', 'Одноразовое'), ('annual', 'Ежегодно')], default='one_time', max_length=20, verbose_name='Повторение')),
                ('color', models.CharField(blank=True, help_text='#RRGGBB', max_length=7, verbose_name='Цвет (hex)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Локация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие отдела',
                'verbose_name_plural': 'События отделов',
                'ordering': ['department', 'start_date'],
                'permissions': [('manage_department_events', 'Can create/update/delete department events')],
            },
        ),
        migrations.AddField(
            model_name='companyevent',
            name='color',
            field=models.CharField(blank=True, help_text='#RRGGBB', max_length=7, verbose_name='Цвет (hex)'),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyevent',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_events_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddIndex(
            model_name='companyevent',
            index=models.Index(fields=['date'], name='calendar_ap_date_4971b4_idx'),
        ),
        migrations.AddIndex(
            model_name='companyevent',
            index=models.Index(fields=['recurrence', 'date'], name='calendar_ap_recurre_a9d265_idx'),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_events_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='employees.department', verbose_name='Отдел'),
        ),
        migrations.AddIndex(
            model_name='departmentevent',
            index=models.Index(fields=['department', 'start_date'], name='calendar_ap_departm_bd9d50_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentevent',
            index=models.Index(fields=['department', 'recurrence', 'start_date'], name='calendar_ap_departm_8b7c66_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentevent',
            index=models.Index(fields=['start_date', 'end_date'], name='calendar_ap_start_d_1ab78d_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentevent',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='dept_event_date_range_valid'),
        ),
    ]
