# Generated by Django 5.2.4 on 2025-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_departmentevent_companyevent_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentevent',
            options={'ordering': ['department', 'start_date'], 'permissions': [('manage_department_events', 'Может создавать/обновлять/ удалять события отдела')], 'verbose_name': 'Событие отдела', 'verbose_name_plural': 'События отделов'},
        ),
    ]
