# Generated by Django 5.2.4 on 2025-09-09 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_event_delete_departmentevent_and_more'),
        ('employees', '0024_alter_departmentpermission_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='CalendarEvent',
        ),
        migrations.RemoveField(
            model_name='companyevent',
            name='created_by',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ap_departm_ff088c_idx',
            old_name='calendar_ap_departm_ef1b03_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ap_departm_031e6f_idx',
            old_name='calendar_ap_departm_cb628e_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ap_start_d_8880a8_idx',
            old_name='calendar_ap_start_d_f4158f_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ap_start_d_f6dd7c_idx',
            old_name='calendar_ap_start_d_e5cf45_idx',
        ),
        migrations.DeleteModel(
            name='CompanyEvent',
        ),
    ]
