# Generated by Django 5.2.4 on 2025-09-09 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_alter_calendarevent_options_and_more'),
        ('employees', '0024_alter_departmentpermission_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(blank=True, db_index=True, help_text="Технический ключ связи с внешним объектом, напр. 'employee:<id>:birthday'", max_length=120, verbose_name='Источник события'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['source'], name='calendar_ap_source_856f30_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source', ''), _negated=True), fields=('source',), name='cal_event_source_unique'),
        ),
    ]
