# Generated by Django 5.2.4 on 2025-09-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_calendarevent_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['department', 'start_date', 'start_time'], 'verbose_name': 'Событие календаря', 'verbose_name_plural': 'События календаря'},
        ),
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='cal_event_date_time_range_valid',
        ),
    ]
