# Generated by Django 5.2.4 on 2026-02-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_calendarsubscription_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubscription',
            name='color_override',
            field=models.CharField(blank=True, help_text='Переопределяет цвет календаря', max_length=7, null=True, verbose_name='Свой цвет'),
        ),
    ]
