# Generated by Django 5.2.4 on 2026-04-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userauthsession',
            new_name='api_useraut_user_id_70da51_idx',
            old_name='api_useraut_user_id_1e9721_idx',
        ),
        migrations.RenameIndex(
            model_name='userauthsession',
            new_name='api_useraut_user_id_5a84c5_idx',
            old_name='api_useraut_user_id_82cdaa_idx',
        ),
    ]
