# Generated by Django 5.2.4 on 2025-08-07 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('employees', '0006_alter_employeedepartment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной чат'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True), ('type', 'global')), fields=('type',), name='unique_main_global_chat'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True), ('type', 'department')), fields=('type', 'department'), name='unique_main_department_chat'),
        ),
    ]
