# Generated by Django 5.2.4 on 2025-08-08 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_chat_is_main_chat_unique_main_global_chat_and_more'),
        ('employees', '0009_alter_employeedepartment_date_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Указывается только для чатов отдела', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Используется только для личных чатов', related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
