# Generated by Django 5.2.4 on 2025-08-20 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_chatreadstate'),
        ('employees', '0010_historicalemployeeaction_historicalemployeeposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatreadstate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Личный'), ('department', 'Отдел'), ('global', 'Глобальный')], db_index=True, max_length=16, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', 'is_main'], name='communicati_type_9ee446_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['department'], name='communicati_departm_e2e705_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['created_at'], name='communicati_created_a80df3_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='uniq_chatreadstate_chat_user'),
        ),
    ]
