# Generated by Django 5.2.4 on 2025-11-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_chatreadstate_unique_together_alter_chat_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_avatars/%Y/%m/', verbose_name='Аватар чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='include_all_employees',
            field=models.BooleanField(default=False, help_text='Для анонсов и общих чатов', verbose_name='Включить всех сотрудников'),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, help_text='Для групповых/канальных чатов', max_length=255, verbose_name='Название чата'),
        ),
    ]
