# Generated by Django 5.2.4 on 2025-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_chat_avatar_chat_created_by_chat_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Личный'), ('group', 'Групповой'), ('department', 'Отдел'), ('channel', 'Канал'), ('announcement', 'Объявления'), ('global', 'Глобальный')], db_index=True, max_length=16, verbose_name='Тип чата'),
        ),
    ]
