# Generated by Django 5.2.4 on 2025-11-20 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_chat_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплен')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрепления')),
                ('pin_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления')),
                ('custom_name', models.CharField(blank=True, max_length=255, verbose_name='Свое название')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыт')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='communications.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки чата',
                'verbose_name_plural': 'Настройки чатов',
                'ordering': ['-is_pinned', '-pinned_at'],
                'indexes': [models.Index(fields=['user', 'is_pinned'], name='communicati_user_id_2d5887_idx'), models.Index(fields=['chat', 'user'], name='communicati_chat_id_86bcb6_idx')],
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
