# Generated by Django 5.2.4 on 2025-11-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_chatusersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Кто удалил (может отличаться от автора)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, help_text='История редактирования [{timestamp, old_content}, ...]'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_cross_chat',
            field=models.BooleanField(default=False, help_text='Сообщение отправлено не участником чата'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, help_text="Формат: {'👍': [user_id1, user_id2], '❤️': [user_id3]}"),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Простая связь для быстрого доступа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='communications.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='system_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные для системных сообщений'),
        ),
        migrations.AddField(
            model_name='message',
            name='system_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_root',
            field=models.ForeignKey(blank=True, help_text='Корневое сообщение треда', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='communications.message'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='communicati_chat_id_10091d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_deleted', 'created_at'], name='communicati_chat_id_7cdaea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', 'created_at'], name='communicati_author__e3ed1d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_root', 'created_at'], name='communicati_thread__951aef_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_pinned', 'chat'], name='communicati_is_pinn_8cd754_idx'),
        ),
    ]
