# Generated by Django 5.2.4 on 2025-11-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_messageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Только чтение'), ('write', 'Чтение и отправка'), ('moderate', 'Модерация')], default='write', max_length=10, verbose_name='Уровень доступа')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда предоставлен доступ')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Если не указано - бессрочно', null=True, verbose_name='Срок действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='communications.chat', verbose_name='Чат')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто предоставил доступ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_access_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Право доступа к чату',
                'verbose_name_plural': 'Права доступа к чатам',
                'indexes': [models.Index(fields=['chat', 'is_active'], name='communicati_chat_id_788c77_idx'), models.Index(fields=['user', 'is_active'], name='communicati_user_id_8402d4_idx')],
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CrossChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('requires_moderation', models.BooleanField(default=True, verbose_name='Требует модерации')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Время модерации')),
                ('moderation_note', models.TextField(blank=True, verbose_name='Заметка модератора')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cross_chat_info', to='communications.message', verbose_name='Сообщение')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_cross_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('target_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_chat_messages', to='communications.chat', verbose_name='Целевой чат')),
            ],
            options={
                'verbose_name': 'Кросс-чат сообщение',
                'verbose_name_plural': 'Кросс-чат сообщения',
                'indexes': [models.Index(fields=['target_chat', 'status'], name='communicati_target__afb50e_idx'), models.Index(fields=['sender', 'sent_at'], name='communicati_sender__d8ea5c_idx'), models.Index(fields=['status', 'requires_moderation'], name='communicati_status_d4dade_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForwardedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время пересылки')),
                ('forward_count', models.IntegerField(default=1, help_text='Сколько раз это сообщение пересылалось', verbose_name='Количество пересылок')),
                ('preserved_content', models.TextField(blank=True, help_text='На случай удаления оригинала', verbose_name='Сохранённый текст')),
                ('preserved_author_name', models.CharField(blank=True, max_length=255, verbose_name='Имя автора оригинала')),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to=settings.AUTH_USER_MODEL, verbose_name='Кто переслал')),
                ('immediate_source', models.ForeignKey(blank=True, help_text='Откуда переслали (может отличаться от original)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.message', verbose_name='Непосредственный источник пересылки')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forward_info', to='communications.message', verbose_name='Пересланное сообщение')),
                ('original_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор оригинального сообщения')),
                ('original_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.chat', verbose_name='Исходный чат')),
                ('original_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_copies', to='communications.message', verbose_name='Самое первое сообщение в цепочке')),
            ],
            options={
                'verbose_name': 'Информация о пересылке',
                'verbose_name_plural': 'Информация о пересылках',
                'indexes': [models.Index(fields=['original_message'], name='communicati_origina_aa3dab_idx'), models.Index(fields=['forwarded_by', 'forwarded_at'], name='communicati_forward_44797e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cross_chat_reply', models.BooleanField(default=False, verbose_name='Ответ из другого чата')),
                ('preserved_text', models.TextField(blank=True, verbose_name='Сохранённый текст оригинала')),
                ('preserved_author_name', models.CharField(blank=True, max_length=255, verbose_name='Имя автора оригинала')),
                ('reply_type', models.CharField(choices=[('inline', 'В потоке'), ('quote', 'С цитатой'), ('thread', 'В треде')], default='inline', max_length=10, verbose_name='Тип ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ответа')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_info', to='communications.message', verbose_name='Сообщение-ответ')),
                ('original_chat', models.ForeignKey(blank=True, help_text='Если ответ был из другого чата', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.chat', verbose_name='Исходный чат')),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_replies', to='communications.message', verbose_name='На какое сообщение ответ')),
            ],
            options={
                'verbose_name': 'Информация об ответе',
                'verbose_name_plural': 'Информация об ответах',
                'indexes': [models.Index(fields=['replied_to'], name='communicati_replied_a35389_idx'), models.Index(fields=['is_cross_chat_reply'], name='communicati_is_cros_be0eee_idx')],
            },
        ),
    ]
