# Generated by Django 5.2.4 on 2025-11-20 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_chataccesspermission_crosschatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('moderator', 'Модератор'), ('member', 'Участник'), ('guest', 'Гость')], default='member', max_length=10, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('is_active', models.BooleanField(default=True, help_text='False если вышел из чата', verbose_name='Активен')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('can_send_messages', models.BooleanField(default=True, verbose_name='Может отправлять сообщения')),
                ('can_add_members', models.BooleanField(default=False, verbose_name='Может добавлять участников')),
                ('can_remove_members', models.BooleanField(default=False, verbose_name='Может удалять участников')),
                ('can_pin_messages', models.BooleanField(default=False, verbose_name='Может закреплять сообщения')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
            },
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='is_typing',
            field=models.BooleanField(default=False, verbose_name='Набирает сообщение'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.message', verbose_name='Последнее прочитанное сообщение'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='typing_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление статуса набора'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='unread_mentions_count',
            field=models.IntegerField(default=0, verbose_name='Непрочитанных упоминаний'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='unread_thread_replies_count',
            field=models.IntegerField(default=0, verbose_name='Непрочитанных ответов в тредах'),
        ),
        migrations.AddIndex(
            model_name='chatreadstate',
            index=models.Index(fields=['chat', 'user', 'is_typing'], name='communicati_chat_id_21af98_idx'),
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communications.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил'),
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(fields=['chat', 'is_active'], name='communicati_chat_id_b9bdc1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(fields=['user', 'is_active'], name='communicati_user_id_1365f8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(fields=['chat', 'role'], name='communicati_chat_id_3bb35b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmembership',
            unique_together={('chat', 'user')},
        ),
    ]
