# Generated by Django 5.2.4 on 2025-11-30 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_chatmembership_chatreadstate_is_typing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('wechat', 'WeChat')], max_length=20, unique=True, verbose_name='Тип мессенджера')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включена')),
                ('status', models.CharField(choices=[('inactive', 'Не активна'), ('active', 'Активна'), ('error', 'Ошибка')], default='inactive', max_length=20, verbose_name='Статус')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API ключ')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API секрет')),
                ('webhook_url', models.URLField(blank=True, max_length=500, verbose_name='Webhook URL')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Отправлено сообщений')),
                ('messages_received', models.IntegerField(default=0, verbose_name='Получено сообщений')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Интеграция с мессенджером',
                'verbose_name_plural': 'Интеграции с мессенджерами',
                'indexes': [models.Index(fields=['messenger_type', 'is_enabled'], name='communicati_messeng_c8457c_idx'), models.Index(fields=['status'], name='communicati_status_7fb887_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessengerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, verbose_name='ID в мессенджере')),
                ('external_username', models.CharField(blank=True, max_length=200, verbose_name='Имя в мессенджере')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='communications.messengerintegration', verbose_name='Интеграция')),
            ],
            options={
                'verbose_name': 'Аккаунт в мессенджере',
                'verbose_name_plural': 'Аккаунты в мессенджерах',
            },
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, verbose_name='ID в мессенджере')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=10, verbose_name='Направление')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('content', models.TextField(verbose_name='Текст')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения')),
                ('external_timestamp', models.DateTimeField(verbose_name='Время в мессенджере')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Синхронизировано')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_messages', to='communications.messengerintegration', verbose_name='Интеграция')),
                ('internal_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_sync', to='communications.message', verbose_name='Внутреннее сообщение')),
                ('recipient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='communications.messengeraccount', verbose_name='Получатель')),
                ('sender_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='communications.messengeraccount', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение из мессенджера',
                'verbose_name_plural': 'Сообщения из мессенджеров',
                'ordering': ['-external_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='messengeraccount',
            index=models.Index(fields=['user', 'integration'], name='communicati_user_id_acfa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='messengeraccount',
            index=models.Index(fields=['external_id'], name='communicati_externa_2dfbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='messengeraccount',
            index=models.Index(fields=['phone_number'], name='communicati_phone_n_8df544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messengeraccount',
            unique_together={('integration', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='messengermessage',
            index=models.Index(fields=['integration', 'external_timestamp'], name='communicati_integra_af291e_idx'),
        ),
        migrations.AddIndex(
            model_name='messengermessage',
            index=models.Index(fields=['sender_account', 'external_timestamp'], name='communicati_sender__496a25_idx'),
        ),
        migrations.AddIndex(
            model_name='messengermessage',
            index=models.Index(fields=['status'], name='communicati_status_9d880b_idx'),
        ),
        migrations.AddIndex(
            model_name='messengermessage',
            index=models.Index(fields=['-synced_at'], name='communicati_synced__4496a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messengermessage',
            unique_together={('integration', 'external_id')},
        ),
    ]
