# Generated by Django 5.2.4 on 2025-11-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_messengerintegration_messengeraccount_and_more'),
    ]

    operations = [
        # Сначала удаляем индексы, которые зависят от полей
        migrations.RemoveIndex(
            model_name='messengermessage',
            name='communicati_integra_af291e_idx',
        ),
        migrations.RemoveIndex(
            model_name='messengermessage',
            name='communicati_sender__496a25_idx',
        ),
        migrations.RemoveIndex(
            model_name='messengermessage',
            name='communicati_status_9d880b_idx',
        ),
        migrations.RemoveIndex(
            model_name='messengermessage',
            name='communicati_synced__4496a8_idx',
        ),
        # Удаляем unique_together
        migrations.AlterUniqueTogether(
            name='messengermessage',
            unique_together=None,
        ),
        # Теперь удаляем поля
        migrations.RemoveField(
            model_name='messengermessage',
            name='sender_account',
        ),
        migrations.RemoveField(
            model_name='messengermessage',
            name='recipient_account',
        ),
        migrations.RemoveField(
            model_name='messengermessage',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='messengermessage',
            name='internal_message',
        ),
        # Удаляем индексы MessengerAccount
        migrations.RemoveIndex(
            model_name='messengeraccount',
            name='communicati_user_id_acfa5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='messengeraccount',
            name='communicati_externa_2dfbcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='messengeraccount',
            name='communicati_phone_n_8df544_idx',
        ),
        # Удаляем unique_together MessengerAccount
        migrations.AlterUniqueTogether(
            name='messengeraccount',
            unique_together=None,
        ),
        # Удаляем поля MessengerAccount
        migrations.RemoveField(
            model_name='messengeraccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messengeraccount',
            name='integration',
        ),
        # Удаляем индексы MessengerIntegration
        migrations.RemoveIndex(
            model_name='messengerintegration',
            name='communicati_messeng_c8457c_idx',
        ),
        migrations.RemoveIndex(
            model_name='messengerintegration',
            name='communicati_status_7fb887_idx',
        ),
        # Теперь можно удалить модели
        migrations.DeleteModel(
            name='MessengerMessage',
        ),
        migrations.DeleteModel(
            name='MessengerAccount',
        ),
        migrations.DeleteModel(
            name='MessengerIntegration',
        ),
    ]
