# Generated by Django 5.2.4 on 2025-11-30 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_remove_messengermessage_sender_account_and_more'),
        ('employees', '0034_alter_employee_telegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AddField(
            model_name='chat',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_chats', to=settings.AUTH_USER_MODEL, verbose_name='Кто заблокировал'),
        ),
        migrations.AddField(
            model_name='chat',
            name='can_reply',
            field=models.BooleanField(default=True, help_text='False для announcement (только реакции)', verbose_name='Можно отвечать'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Для announcement: заблокирован администратором, скрыт у всех', verbose_name='Заблокирован'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'announcement')), fields=('type', 'created_by'), name='unique_announcement_per_user'),
        ),
    ]
