# Generated by Django 5.2.4 on 2025-11-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_chat_blocked_at_chat_blocked_by_chat_can_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reactions',
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Unicode эмодзи (например: 👍, ❤️, 😂)', max_length=10, verbose_name='Эмодзи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='communications.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на сообщение',
                'verbose_name_plural': 'Реакции на сообщения',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='communicati_message_f5b4e6_idx'), models.Index(fields=['message', 'user'], name='communicati_message_8c7214_idx'), models.Index(fields=['created_at'], name='communicati_created_3e5423_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
