# Generated by Django 5.2.4 on 2025-11-30 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_remove_message_reactions_messagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from_author',
            field=models.ForeignKey(blank=True, help_text='Автор исходного сообщения при пересылке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from_message_id',
            field=models.IntegerField(blank=True, help_text='ID исходного сообщения при пересылке', null=True),
        ),
    ]
