# Generated by Django 5.2.4 on 2025-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0017_add_forward_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from_chat_name',
            field=models.CharField(blank=True, help_text='Название исходного чата при пересылке', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from_created_at',
            field=models.DateTimeField(blank=True, help_text='Дата создания исходного сообщения при пересылке', null=True),
        ),
    ]
