# Generated by Django 5.2.4 on 2025-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0019_add_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Unicode эмодзи (например: 👍, ❤️, 😂)', max_length=10, unique=True, verbose_name='Эмодзи')),
                ('name', models.CharField(help_text="Человекочитаемое название (например: 'Лайк', 'Сердце')", max_length=50, verbose_name='Название')),
                ('order', models.IntegerField(default=0, help_text='Меньше = выше в списке', verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли эту реакцию пользователям', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Доступная реакция',
                'verbose_name_plural': 'Доступные реакции',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='communicati_message_6f2b88_idx',
            old_name='comm_msg_idx_poll',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='communicati_author__d3b17c_idx',
            old_name='comm_auth_created_poll',
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='communicati_is_clos_6320c7_idx',
            old_name='comm_closed_closes_poll',
        ),
        migrations.RenameIndex(
            model_name='polloption',
            new_name='communicati_poll_id_471041_idx',
            old_name='comm_poll_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='communicati_poll_id_dc4395_idx',
            old_name='comm_poll_voter_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='communicati_option__2d5cef_idx',
            old_name='comm_option_idx',
        ),
        migrations.AlterField(
            model_name='poll',
            name='allows_custom_answers',
            field=models.BooleanField(default=False, help_text='Пользователи могут добавить свой вариант ответа', verbose_name='Разрешить свои варианты'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Голосование автоматически закроется в указанное время', null=True, verbose_name='Автоматическое закрытие'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Не показывать кто голосовал', verbose_name='Анонимное голосование'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_multiple_choice',
            field=models.BooleanField(default=False, help_text='Можно выбрать несколько вариантов', verbose_name='Множественный выбор'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_quiz',
            field=models.BooleanField(default=False, help_text='Только один правильный ответ, показывается после голосования', verbose_name='Викторина'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='total_voters',
            field=models.IntegerField(default=0, help_text='Количество уникальных пользователей, проголосовавших', verbose_name='Всего проголосовало'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Для викторин', verbose_name='Правильный ответ'),
        ),
        migrations.AddIndex(
            model_name='availablereaction',
            index=models.Index(fields=['is_active', 'order'], name='communicati_is_acti_124af4_idx'),
        ),
    ]
