# Generated by Django 5.2.4 on 2026-01-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0022_alter_messageattachment_height_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatAccessPermission',
        ),
        migrations.DeleteModel(
            name='CrossChatMessage',
        ),
        migrations.DeleteModel(
            name='MessageReply',
        ),
    ]
