# Generated by Django 5.2.4 on 2026-01-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0023_remove_crosschatmessage_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForwardedMessage',
        ),
    ]
