# Generated by Django 5.2.4 on 2026-01-15 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0024_delete_forwardedmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время редактирования')),
                ('previous_content', models.TextField(verbose_name='Предыдущий текст')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто отредактировал')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history_records', to='communications.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запись истории редактирования',
                'verbose_name_plural': 'История редактирования сообщений',
                'ordering': ['edited_at'],
                'indexes': [models.Index(fields=['message', 'edited_at'], name='communicati_message_761cf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageForwardMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время пересылки')),
                ('forward_count', models.IntegerField(default=1, help_text='Сколько раз пересылалось', verbose_name='Количество пересылок')),
                ('original_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания оригинала')),
                ('original_chat_name', models.CharField(blank=True, max_length=255, verbose_name='Название оригинального чата')),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to=settings.AUTH_USER_MODEL, verbose_name='Кто переслал')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forward_metadata', to='communications.message', verbose_name='Пересланное сообщение')),
                ('original_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор оригинала')),
                ('original_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.chat', verbose_name='Оригинальный чат')),
                ('original_message', models.ForeignKey(blank=True, help_text='Самое первое сообщение в цепочке пересылок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_copies', to='communications.message', verbose_name='Оригинальное сообщение')),
            ],
            options={
                'verbose_name': 'Метаданные пересылки',
                'verbose_name_plural': 'Метаданные пересылок',
                'indexes': [models.Index(fields=['original_message'], name='communicati_origina_41ca01_idx'), models.Index(fields=['forwarded_by', 'forwarded_at'], name='communicati_forward_60dc34_idx')],
            },
        ),
    ]
