# Generated by Django 5.2.4 on 2026-01-15 08:34

from django.db import migrations
from django.utils.dateparse import parse_datetime


def migrate_edit_history(apps, schema_editor):
    """Перенос истории редактирования из JSON в MessageEditHistory"""
    Message = apps.get_model('communications', 'Message')
    MessageEditHistory = apps.get_model('communications', 'MessageEditHistory')
    
    messages_with_history = Message.objects.filter(is_edited=True).exclude(edit_history=[])
    
    for message in messages_with_history:
        if not message.edit_history:
            continue
            
        # edit_history формат: [{"timestamp": "...", "old_content": "..."}, ...]
        for entry in message.edit_history:
            try:
                # Парсим timestamp
                if isinstance(entry.get('timestamp'), str):
                    edited_at = parse_datetime(entry['timestamp'])
                    if not edited_at:
                        # Если не удалось распарсить, используем edited_at сообщения
                        edited_at = message.edited_at or message.created_at
                else:
                    edited_at = entry.get('timestamp', message.edited_at or message.created_at)
                
                MessageEditHistory.objects.create(
                    message=message,
                    edited_at=edited_at,
                    previous_content=entry.get('old_content', ''),
                    edited_by=message.author  # Предполагаем что автор редактировал
                )
            except Exception as e:
                # Логируем ошибку но продолжаем
                print(f"Error migrating edit history for message {message.id}: {e}")


def migrate_forward_metadata(apps, schema_editor):
    """Перенос метаданных пересылки из полей Message в MessageForwardMetadata"""
    Message = apps.get_model('communications', 'Message')
    MessageForwardMetadata = apps.get_model('communications', 'MessageForwardMetadata')
    
    forwarded_messages = Message.objects.filter(is_forwarded=True)
    
    for message in forwarded_messages:
        # Пропускаем если метаданные уже созданы
        if hasattr(message, 'forward_metadata'):
            continue
            
        try:
            # Получаем оригинальное сообщение по ID
            original_message = None
            if message.forwarded_from_message_id:
                try:
                    original_message = Message.objects.get(id=message.forwarded_from_message_id)
                except Message.DoesNotExist:
                    pass
            
            MessageForwardMetadata.objects.create(
                message=message,
                original_message=original_message,
                original_author=message.forwarded_from_author,
                forwarded_by=message.author,
                original_created_at=message.forwarded_from_created_at,
                original_chat_name=message.forwarded_from_chat_name or '',
                forward_count=1  # По умолчанию 1
            )
        except Exception as e:
            # Логируем ошибку но продолжаем
            print(f"Error migrating forward metadata for message {message.id}: {e}")


def reverse_migrate_edit_history(apps, schema_editor):
    """Откат: перенос MessageEditHistory обратно в JSON"""
    Message = apps.get_model('communications', 'Message')
    MessageEditHistory = apps.get_model('communications', 'MessageEditHistory')
    
    for message in Message.objects.filter(is_edited=True):
        history_records = MessageEditHistory.objects.filter(message=message).order_by('edited_at')
        
        edit_history = []
        for record in history_records:
            edit_history.append({
                'timestamp': record.edited_at.isoformat(),
                'old_content': record.previous_content
            })
        
        message.edit_history = edit_history
        message.save(update_fields=['edit_history'])


def reverse_migrate_forward_metadata(apps, schema_editor):
    """Откат: данные уже в Message полях, просто удаляем MessageForwardMetadata"""
    pass  # Данные остаются в полях Message


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0025_messageedithistory_messageforwardmetadata'),
    ]

    operations = [
        migrations.RunPython(migrate_edit_history, reverse_migrate_edit_history),
        migrations.RunPython(migrate_forward_metadata, reverse_migrate_forward_metadata),
    ]
