# Generated by Django 5.2.4 on 2026-01-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0026_migrate_edit_and_forward_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edit_history',
        ),
        migrations.RemoveField(
            model_name='message',
            name='forwarded_from_author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='forwarded_from_chat_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='forwarded_from_created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='forwarded_from_message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread_reply_count',
        ),
    ]
