# Generated by Django 5.2.4 on 2026-02-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0028_remove_last_read_at_and_unused_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatreadstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, help_text='Обновляется автоматически при загрузке сообщений (Telegram-style)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.message', verbose_name='Последнее прочитанное сообщение'),
        ),
        migrations.AddIndex(
            model_name='chatreadstate',
            index=models.Index(fields=['last_read_message'], name='communicati_last_re_2f5f7e_idx'),
        ),
    ]
