# Generated by Django 5.2.4 on 2026-03-10 15:00

from django.conf import settings
from django.db import migrations, models


def recalculate_unread_counts(apps, schema_editor):
    """
    Пересчитываем unread_count для всех существующих ChatReadState записей.
    Это может занять время на больших данных, но выполняется один раз.
    """
    ChatReadState = apps.get_model('communications', 'ChatReadState')
    Message = apps.get_model('communications', 'Message')
    
    total = ChatReadState.objects.count()
    print(f"\n🔄 Пересчет unread_count для {total} записей ChatReadState...")
    
    updated = 0
    for read_state in ChatReadState.objects.select_related('chat', 'user').iterator(chunk_size=100):
        # Считаем непрочитанные сообщения
        messages_qs = Message.objects.filter(
            chat_id=read_state.chat_id,
            is_deleted=False
        ).exclude(author_id=read_state.user_id)
        
        if read_state.last_read_message_id:
            # Считаем сообщения с ID больше последнего прочитанного
            count = messages_qs.filter(id__gt=read_state.last_read_message_id).count()
        else:
            # Если не было прочтений - все сообщения непрочитаны
            count = messages_qs.count()
        
        read_state.unread_count = count
        read_state.save(update_fields=['unread_count'])
        
        updated += 1
        if updated % 100 == 0:
            print(f"  Обработано: {updated}/{total}")
    
    print(f"✅ Обновлено {updated} записей")


def reverse_recalculate(apps, schema_editor):
    """При откате миграции просто обнуляем счетчики"""
    ChatReadState = apps.get_model('communications', 'ChatReadState')
    ChatReadState.objects.update(unread_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0029_alter_chatreadstate_last_read_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreadstate',
            name='unread_count',
            field=models.IntegerField(default=0, help_text='Кешированное значение для производительности. Обновляется при новых сообщениях и прочтении.', verbose_name='Непрочитанных сообщений'),
        ),
        migrations.AddIndex(
            model_name='chatreadstate',
            index=models.Index(fields=['user', 'unread_count'], name='communicati_user_id_241b5b_idx'),
        ),
        # Пересчитываем существующие значения
        migrations.RunPython(recalculate_unread_counts, reverse_recalculate),
    ]
