# Generated by Django 5.2.4 on 2026-03-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0030_chatreadstate_unread_count_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0041_alter_departmentpermission_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of related object (e.g., Department, Project, Team)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Context type'),
        ),
        migrations.AddField(
            model_name='chat',
            name='context_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Context object ID'),
        ),
        migrations.AddField(
            model_name='chat',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional chat metadata (extensible)', verbose_name='Extra data'),
        ),
        migrations.AddField(
            model_name='chat',
            name='flags',
            field=models.JSONField(blank=True, default=dict, help_text="Custom flags: {'is_primary': true, 'is_archived': false, etc.}", verbose_name='Flags'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Личный'), ('group', 'Групповой'), ('department', 'Отдел'), ('channel', 'Канал'), ('announcement', 'Объявления'), ('global', 'Глобальный')], db_index=True, help_text='Chat type: private, group, channel, announcement, department, global', max_length=32, verbose_name='Тип чата'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['context_content_type', 'context_object_id'], name='chat_context_idx'),
        ),
    ]
