# Generated by Django 5.2.4 on 2026-03-11 10:07

from django.db import migrations


def migrate_department_to_context(apps, schema_editor):
    """
    Копирует department → context_object для всех чатов с department.
    """
    Chat = apps.get_model('communications', 'Chat')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Получаем ContentType для модели Department
    try:
        dept_ct = ContentType.objects.get(app_label='employees', model='department')
    except ContentType.DoesNotExist:
        print("ContentType для Department не найден, пропускаем миграцию")
        return

    # Находим все чаты с department
    chats_with_dept = Chat.objects.filter(department__isnull=False)

    count = 0
    for chat in chats_with_dept:
        chat.context_content_type = dept_ct
        chat.context_object_id = chat.department_id
        chat.save(update_fields=['context_content_type', 'context_object_id'])
        count += 1

    print(f"Мигрировано {count} чатов: department → context_object")


def reverse_migrate(apps, schema_editor):
    """
    Откат: копирует context_object → department для Department объектов.
    """
    Chat = apps.get_model('communications', 'Chat')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        dept_ct = ContentType.objects.get(app_label='employees', model='department')
    except ContentType.DoesNotExist:
        return

    chats_with_context = Chat.objects.filter(
        context_content_type=dept_ct,
        context_object_id__isnull=False
    )

    count = 0
    for chat in chats_with_context:
        chat.department_id = chat.context_object_id
        chat.save(update_fields=['department'])
        count += 1

    print(f"Откат: восстановлено {count} чатов: context_object → department")


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0031_add_universal_context_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(migrate_department_to_context, reverse_code=reverse_migrate),
    ]
