# Generated by Django 5.2.4 on 2026-03-11 10:08

from django.db import migrations


def migrate_is_main_to_flags(apps, schema_editor):
    """
    Копирует is_main → flags['is_primary'].
    """
    Chat = apps.get_model('communications', 'Chat')

    chats_with_is_main = Chat.objects.filter(is_main=True)

    count = 0
    for chat in chats_with_is_main:
        if not chat.flags:
            chat.flags = {}
        chat.flags['is_primary'] = True
        chat.save(update_fields=['flags'])
        count += 1

    print(f"Мигрировано {count} чатов: is_main=True → flags['is_primary']=True")


def reverse_migrate(apps, schema_editor):
    """
    Откат: копирует flags['is_primary'] → is_main.
    """
    Chat = apps.get_model('communications', 'Chat')

    all_chats = Chat.objects.all()

    count = 0
    for chat in all_chats:
        if chat.flags and chat.flags.get('is_primary'):
            chat.is_main = True
            chat.save(update_fields=['is_main'])
            count += 1

    print(f"Откат: восстановлено {count} чатов: flags['is_primary'] → is_main")


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0032_migrate_department_to_context'),
    ]

    operations = [
        migrations.RunPython(migrate_is_main_to_flags, reverse_code=reverse_migrate),
    ]
