# Generated by Django 5.2.4 on 2026-03-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0033_migrate_is_main_to_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='include_all_employees',
            new_name='include_all_users',
        ),
    ]
