# Generated by Django 5.2.4 on 2026-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0034_rename_include_all_employees'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_main_department_chat',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='communicati_departm_e2e705_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='department',
        ),
        migrations.AlterField(
            model_name='chat',
            name='include_all_users',
            field=models.BooleanField(default=False, help_text='Для анонсов и общих чатов', verbose_name='Включить всех пользователей'),
        ),
    ]
