# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0038_alter_chat_participants_alter_chatmembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="context_object_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                verbose_name="Context object ID",
            ),
        ),
    ]
