# Generated by Django 5.2.4 on 2025-11-21 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotificationsettings_email_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='email_frequency',
            field=models.CharField(choices=[('instant', 'Мгновенно'), ('daily', 'Ежедневный дайджест'), ('weekly', 'Еженедельный дайджест')], default='instant', help_text='Как часто отправлять уведомления на email (только если email включен)', max_length=20, verbose_name='Частота email рассылки'),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный ID пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, help_text='@username пользователя в Telegram', max_length=100, null=True, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия в Telegram')),
                ('link_code', models.CharField(blank=True, help_text='Временный код для привязки аккаунта', max_length=10, null=True, unique=True, verbose_name='Код привязки')),
                ('link_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Код создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_blocked', models.BooleanField(default=False, help_text='Пользователь заблокировал бота', verbose_name='Заблокирован')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее взаимодействие')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram аккаунт',
                'verbose_name_plural': 'Telegram аккаунты',
                'db_table': 'notifications_telegram_user',
                'indexes': [models.Index(fields=['telegram_id'], name='notificatio_telegra_4cbfaa_idx'), models.Index(fields=['link_code'], name='notificatio_link_co_58a9a9_idx'), models.Index(fields=['user'], name='notificatio_user_id_d2ff2e_idx')],
            },
        ),
    ]
