# Generated by Django 5.2.4 on 2026-01-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_telegramuser_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='URL для отправки push уведомлений', max_length=512, verbose_name='Push Endpoint')),
                ('auth_key', models.CharField(help_text='Ключ авторизации (subscription.keys.auth)', max_length=512, verbose_name='Auth Key')),
                ('p256dh_key', models.CharField(help_text='Ключ шифрования (subscription.keys.p256dh)', max_length=512, verbose_name='P256DH Key')),
                ('user_agent', models.TextField(blank=True, help_text='Браузер и ОС', verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('error_count', models.IntegerField(default=0, verbose_name='Счётчик ошибок')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Web Push подписка',
                'verbose_name_plural': 'Web Push подписки',
                'db_table': 'notifications_web_push_subscription',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
