# Generated by Django 5.2.4 on 2026-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_web_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpushsubscription',
            name='device_name',
            field=models.CharField(blank=True, default='', help_text='iOS Device, Windows (Chrome), macOS (Safari), и т.д.', max_length=255, verbose_name='Название устройства'),
        ),
    ]
