# Generated by Django 5.2.4 on 2026-02-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_procurement_notification_types'),
        ('notifications', '0006_add_device_name'),
    ]

    operations = [
    ]
