# Generated by Django 5.2.4 on 2026-02-28 12:04

from django.db import migrations


def add_document_related_notification_type(apps, schema_editor):
    """
    Добавляет новый тип уведомления для связанных документов.
    """
    NotificationCategory = apps.get_model('notifications', 'NotificationCategory')
    NotificationType = apps.get_model('notifications', 'NotificationType')

    # Получаем категорию "Документы"
    try:
        documents_category = NotificationCategory.objects.get(code='documents')
    except NotificationCategory.DoesNotExist:
        # Если категории нет, создаём её
        documents_category = NotificationCategory.objects.create(
            code='documents',
            name='Документы',
            description='Уведомления о документах',
            icon='bi-file-earmark-text',
            color='primary',
            is_active=True,
            order=2
        )

    # Создаём новый тип уведомления (если его ещё нет)
    NotificationType.objects.get_or_create(
        code='document_related',
        defaults={
            'category': documents_category,
            'name': 'Связанный документ',
            'description': 'Уведомление о добавлении связанного документа',
            'default_enabled': True,
            'default_channels': {
                'web': True,
                'email': False,
                'telegram': False
            },
            'priority': 'normal',
            'is_required': False,
            'is_groupable': True,
            'grouping_window_minutes': 10,
            'is_active': True,
        }
    )

    # Также добавим тип для ответов на комментарии (если нужен отдельный)
    NotificationType.objects.get_or_create(
        code='document_comment_reply',
        defaults={
            'category': documents_category,
            'name': 'Ответ на комментарий',
            'description': 'Уведомление об ответе на ваш комментарий к документу',
            'default_enabled': True,
            'default_channels': {
                'web': True,
                'email': False,
                'telegram': False
            },
            'priority': 'normal',
            'is_required': False,
            'is_groupable': True,
            'grouping_window_minutes': 5,
            'is_active': True,
        }
    )


def remove_document_related_notification_type(apps, schema_editor):
    """
    Откат: удаляет добавленный тип уведомления.
    """
    NotificationType = apps.get_model('notifications', 'NotificationType')

    NotificationType.objects.filter(
        code__in=['document_related', 'document_comment_reply']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_migrate_webpush_to_library'),
    ]

    operations = [
        migrations.RunPython(
            add_document_related_notification_type,
            remove_document_related_notification_type
        ),
    ]
