# Generated by Django 5.2.4 on 2025-08-12 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employeedepartment_date_from_and_more'),
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Комментарий к заявке',
                'verbose_name_plural': 'Комментарии к заявкам',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий'),
        ),
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requests/attachments/%Y/%m/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='request',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Решение принято'),
        ),
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', 'created_at'], name='requests_ap_status_63c030_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['type', 'created_at'], name='requests_ap_type_6ecad2_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['employee', 'created_at'], name='requests_ap_employe_4f9b37_idx'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__isnull', True), ('date_from__isnull', True), ('date_from__lte', models.F('date_to')), _connector='OR'), name='request_date_range_valid'),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests_app.request', verbose_name='Заявка'),
        ),
        migrations.AddIndex(
            model_name='requestcomment',
            index=models.Index(fields=['created_at'], name='requests_ap_created_43572e_idx'),
        ),
    ]
