# Generated by Django 5.2.4 on 2025-08-12 06:01

import django.core.validators
import requests_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employeedepartment_date_from_and_more'),
        ('requests_app', '0002_requestcomment_request_approver_request_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requests/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']), requests_app.models.attachment_file_size], verbose_name='Вложение'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['decided_at'], name='requests_ap_decided_1a4c7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approver__isnull', False), ('status__in', ['approved', 'rejected'])), ('status__in', ['draft', 'pending', 'cancelled']), _connector='OR'), name='request_approver_required_on_decision'),
        ),
    ]
