# Generated by Django 5.2.4 on 2025-08-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_remove_request_request_approver_required_on_decision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_requests', 'Can view all requests'), ('can_process_requests', 'Can approve/reject requests')], 'verbose_name': 'Заявление', 'verbose_name_plural': 'Заявления'},
        ),
    ]
