# Generated by Django 5.2.4 on 2025-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_requests', 'Можно просмотреть все заявления'), ('can_process_requests', 'Может одобрять/отклонять заявления')], 'verbose_name': 'Заявление', 'verbose_name_plural': 'Заявления'},
        ),
    ]
