# Generated by Django 5.2.4 on 2025-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_migrate_department_to_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('day_off', 'Отгул'), ('transfer', 'Перевод'), ('dismissal', 'Увольнение'), ('other', 'Другое')], max_length=32, verbose_name='Тип заявления'),
        ),
    ]
