# Generated by Django 5.2.4 on 2026-03-11 19:29

from django.db import migrations
from django.utils import timezone


def migrate_comments_forward(apps, schema_editor):
    """Миграция RequestComment → Communications.Message (ORM)"""
    
    Chat = apps.get_model('communications', 'Chat')
    Message = apps.get_model('communications', 'Message')
    RequestComment = apps.get_model('requests_app', 'RequestComment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        request_ct = ContentType.objects.get(app_label='requests_app', model='request')
    except ContentType.DoesNotExist:
        return
    
    # 1. Создаем чаты для заявок с комментариями
    request_ids_with_comments = RequestComment.objects.values_list('request_id', flat=True).distinct()
    
    for request_id in request_ids_with_comments:
        if Chat.objects.filter(
            type='comments',
            context_content_type=request_ct,
            context_object_id=request_id
        ).exists():
            continue
        
        Chat.objects.create(
            type='comments',
            name=f"Комментарии к заявке #{request_id}",
            description='',
            avatar=None,
            created_by=None,
            can_reply=True,
            flags={'allow_replies': True, 'allow_reactions': True, 'allow_attachments': True, 'allow_editing': True},
            context_content_type=request_ct,
            context_object_id=request_id,
            created_at=timezone.now(),
            is_main=False,
            is_blocked=False,
            include_all_users=False,
            extra_data={}
        )
    
    # 2. Переносим комментарии
    for comment in RequestComment.objects.select_related('author').all():
        try:
            chat = Chat.objects.get(
                type='comments',
                context_content_type=request_ct,
                context_object_id=comment.request_id
            )
        except Chat.DoesNotExist:
            continue
        
        if Message.objects.filter(
            chat=chat,
            author_id=comment.author_id,
            created_at=comment.created_at,
            content=comment.text
        ).exists():
            continue
        
        Message.objects.create(
            chat=chat,
            author_id=comment.author_id,
            content=comment.text or '',
            created_at=comment.created_at,
            is_system=False,
            has_attachments=False,
            is_deleted=False,
            is_edited=False,
            is_pinned=False,
            is_forwarded=False,
            is_cross_chat=False,
            system_type='',
            system_metadata={
                'legacy_comment_id': comment.id,
                'legacy_model': 'requests_app.RequestComment'
            }
        )


def migrate_comments_backward(apps, schema_editor):
    """Откат - удаляем чаты комментариев для заявок"""
    Chat = apps.get_model('communications', 'Chat')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        request_ct = ContentType.objects.get(app_label='requests_app', model='request')
        Chat.objects.filter(
            type='comments',
            context_content_type=request_ct
        ).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_alter_request_type'),
        ('communications', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_comments_forward,
            migrate_comments_backward
        ),
    ]
