# Generated by Django 5.2.4 on 2026-03-11 19:29

from django.db import migrations


def migrate_comments_forward(apps, schema_editor):
    """Миграция RequestComment → Communications.Message (SQL)"""
    
    # 1. Создаем чаты для заявок с комментариями
    schema_editor.execute("""
        INSERT INTO communications_chat (
            type, name, created_by_id, can_reply, flags,
            context_content_type_id, context_object_id,
            created_at, is_main, is_blocked, include_all_users, extra_data
        )
        SELECT DISTINCT
            'comments',
            'Комментарии к заявке #' || rc.request_id,
            NULL::bigint,
            TRUE,
            '{"allow_replies": true, "allow_reactions": true, "allow_attachments": true, "allow_editing": true}'::jsonb,
            (SELECT id FROM django_content_type WHERE app_label='requests_app' AND model='request'),
            rc.request_id,
            NOW(),
            FALSE,
            FALSE,
            FALSE,
            '{}'::jsonb
        FROM requests_app_requestcomment rc
        WHERE NOT EXISTS (
            SELECT 1 FROM communications_chat cc
            WHERE cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='requests_app' AND model='request')
            AND cc.context_object_id = rc.request_id
        )
    """)
    
    # 2. Переносим комментарии
    schema_editor.execute("""
        INSERT INTO communications_message (
            chat_id, author_id, content, created_at,
            is_system, has_attachments,
            is_deleted, is_edited, is_pinned, is_forwarded, is_cross_chat,
            system_metadata
        )
        SELECT 
            cc.id,
            rc.author_id,
            rc.text,
            rc.created_at,
            FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
            jsonb_build_object(
                'legacy_comment_id', rc.id,
                'legacy_model', 'requests_app.RequestComment'
            )
        FROM requests_app_requestcomment rc
        JOIN communications_chat cc ON (
            cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='requests_app' AND model='request')
            AND cc.context_object_id = rc.request_id
        )
        WHERE NOT EXISTS (
            SELECT 1 FROM communications_message m
            WHERE m.chat_id = cc.id
            AND m.author_id = rc.author_id
            AND m.created_at = rc.created_at
            AND m.content = rc.text
        )
    """)


def migrate_comments_backward(apps, schema_editor):
    """Откат - удаляем чаты комментариев для заявок"""
    schema_editor.execute("""
        DELETE FROM communications_chat
        WHERE type = 'comments'
        AND context_content_type_id = (
            SELECT id FROM django_content_type 
            WHERE app_label='requests_app' AND model='request'
        )
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_alter_request_type'),
        ('communications', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_comments_forward,
            migrate_comments_backward
        ),
    ]
