# Generated by Django 5.2.4 on 2026-03-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_migrate_comments_to_communications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestComment',
        ),
    ]
