# Generated by Codex on 2026-04-28

from django.db import migrations, models


REQUEST_TYPE_CHOICES = [
    ("vacation", "Отпуск"),
    ("sick_leave", "Больничный"),
    ("day_off", "Отгул"),
    ("maternity", "Декрет"),
    ("transfer", "Перевод"),
    ("dismissal", "Увольнение"),
    ("other", "Другое"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("requests_app", "0011_remove_requestcomment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="type",
            field=models.CharField(
                choices=REQUEST_TYPE_CHOICES,
                max_length=32,
                verbose_name="Тип заявления",
            ),
        ),
    ]
