# Generated by Django 5.2.4 on 2026-07-16 15:09

import django.core.validators
import requests_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0012_add_maternity_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requests/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), requests_app.models.attachment_mime_validator], verbose_name='Вложение'),
        ),
    ]
