# Generated by Django 5.2.4 on 2026-06-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_guest_document_folder_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestvisit',
            name='admin_comment',
        ),
    ]
