# Generated by Codex on 2026-06-20

from django.conf import settings
from django.db import migrations
from django.utils import timezone


def migrate_guest_comments_forward(apps, schema_editor):
    Chat = apps.get_model("communications", "Chat")
    Message = apps.get_model("communications", "Message")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Guest = apps.get_model("guests", "Guest")

    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    try:
        guest_ct = ContentType.objects.get(app_label="guests", model="guest")
    except ContentType.DoesNotExist:
        return

    fallback_author_id = (
        User.objects.order_by("id").values_list("id", flat=True).first()
    )

    for guest in Guest.objects.exclude(comment="").iterator():
        content = (guest.comment or "").strip()
        if not content:
            continue
        author_id = guest.created_by_id or fallback_author_id
        if not author_id:
            continue
        guest_name = " ".join(
            part
            for part in [
                guest.last_name,
                guest.first_name,
                guest.patronymic,
            ]
            if part
        ) or f"Гость {guest.id}"

        chat, _ = Chat.objects.get_or_create(
            type="comments",
            context_content_type=guest_ct,
            context_object_id=guest.id,
            defaults={
                "name": f"Комментарии: {guest_name[:50]}",
                "created_by_id": author_id,
                "flags": {
                    "allow_replies": True,
                    "allow_reactions": True,
                    "allow_attachments": True,
                    "allow_editing": True,
                },
                "can_reply": True,
                "created_at": guest.created_at or timezone.now(),
            },
        )

        if Message.objects.filter(
            chat=chat,
            system_metadata__legacy_field="guests.Guest.comment",
        ).exists():
            continue

        Message.objects.create(
            chat=chat,
            author_id=author_id,
            content=content,
            created_at=guest.created_at or timezone.now(),
            is_system=False,
            has_attachments=False,
            is_deleted=False,
            is_edited=False,
            is_pinned=False,
            is_forwarded=False,
            is_cross_chat=False,
            system_type="",
            system_metadata={"legacy_field": "guests.Guest.comment"},
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0039_alter_chat_context_object_id_bigint"),
        ("guests", "0007_remove_guestvisit_admin_comment"),
    ]

    operations = [
        migrations.RunPython(
            migrate_guest_comments_forward,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="guest",
            name="comment",
        ),
    ]
