# Generated by Django 5.2.4 on 2025-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HikPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_group_id', models.IntegerField(blank=True, null=True)),
                ('person_type', models.IntegerField(blank=True, null=True)),
                ('person_code', models.CharField(max_length=16, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=512, null=True)),
                ('photo_index', models.IntegerField(blank=True, null=True)),
                ('small_photo_url', models.CharField(blank=True, max_length=512, null=True)),
                ('start_valid_date', models.DateTimeField(blank=True, null=True)),
                ('end_valid_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('object_guid', models.CharField(blank=True, max_length=64, null=True)),
                ('person_from', models.IntegerField(blank=True, null=True)),
                ('rdn', models.CharField(blank=True, max_length=255, null=True)),
                ('dn', models.CharField(blank=True, max_length=255, null=True)),
                ('usn_changed', models.BigIntegerField(blank=True, null=True)),
                ('start_time_differ', models.IntegerField(blank=True, null=True)),
                ('end_time_differ', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HikPersonHeadPic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('standard_head_portrait', models.TextField(blank=True, null=True)),
                ('thumbnail_head_portrait', models.TextField(blank=True, null=True)),
                ('deepmode_head_portrait', models.TextField(blank=True, null=True)),
                ('identi_photo', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_head_pic',
                'managed': False,
            },
        ),
    ]
