# Generated by Django 5.2.4 on 2026-07-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasklinkedobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklinkedobject',
            name='kind',
            field=models.CharField(choices=[('message', 'Сообщение'), ('calendar_event', 'Календарное событие')], max_length=32, verbose_name='Тип связи'),
        ),
    ]
