# Generated by Django 5.2.4 on 2026-07-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasklinkedobject_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создал задачу'), ('updated', 'Обновил задачу'), ('moved', 'Переместил задачу'), ('linked', 'Связал объект'), ('unlinked', 'Убрал связь')], max_length=32, verbose_name='Действие')),
                ('object_kind', models.CharField(blank=True, choices=[('message', 'Сообщение'), ('calendar_event', 'Календарное событие')], max_length=32, verbose_name='Тип объекта')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'История задачи',
                'verbose_name_plural': 'История задач',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_taska_task_id_db425c_idx')],
            },
        ),
    ]
