# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskactivity",
            name="object_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("message", "Сообщение"),
                    ("calendar_event", "Календарное событие"),
                    ("document", "Документ"),
                ],
                max_length=32,
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AlterField(
            model_name="tasklinkedobject",
            name="kind",
            field=models.CharField(
                choices=[
                    ("message", "Сообщение"),
                    ("calendar_event", "Календарное событие"),
                    ("document", "Документ"),
                ],
                max_length=32,
                verbose_name="Тип связи",
            ),
        ),
    ]
