# Generated by Django 5.2.4 on 2026-07-16 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskusersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Создал задачу'), ('updated', 'Обновил задачу'), ('moved', 'Переместил задачу'), ('linked', 'Связал объект'), ('unlinked', 'Убрал связь'), ('attachment_added', 'Добавил файл'), ('attachment_removed', 'Удалил файл')], max_length=32, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='Размер файла (байты)')),
                ('mime_type', models.CharField(blank=True, max_length=255, verbose_name='MIME-тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='Задача')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение задачи',
                'verbose_name_plural': 'Вложения задач',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='tasks_taska_task_id_3aa34c_idx')],
            },
        ),
    ]
