# Generated by Django 5.2.4 on 2026-07-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_taskactivity_action_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='object_kind',
            field=models.CharField(blank=True, choices=[('post', 'Новость'), ('message', 'Сообщение'), ('calendar_event', 'Календарное событие'), ('document', 'Документ'), ('request', 'Заявление'), ('procurement_request', 'Заявка на закупку'), ('employee', 'Сотрудник'), ('guest', 'Гость'), ('guest_visit', 'Заявка на гостевой визит'), ('attendance_record', 'Запись посещаемости'), ('external_link', 'Внешняя ссылка')], max_length=32, verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='TaskExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_external_links', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Внешняя ссылка задачи',
                'verbose_name_plural': 'Внешние ссылки задач',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='tasks_taske_task_id_d49775_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'url'), name='uniq_task_external_link')],
            },
        ),
    ]
