# Generated by Django 5.2.4 on 2026-07-16 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_taskactivity_object_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Создал задачу'), ('updated', 'Обновил задачу'), ('moved', 'Переместил задачу'), ('linked', 'Связал объект'), ('unlinked', 'Убрал связь'), ('attachment_added', 'Добавил файл'), ('attachment_removed', 'Удалил файл'), ('checklist_item_added', 'Добавил пункт чек-листа'), ('checklist_item_updated', 'Изменил пункт чек-листа'), ('checklist_item_completed', 'Выполнил пункт чек-листа'), ('checklist_item_reopened', 'Вернул пункт чек-листа в работу'), ('checklist_item_removed', 'Удалил пункт чек-листа')], max_length=32, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='object_kind',
            field=models.CharField(blank=True, choices=[('post', 'Новость'), ('message', 'Сообщение'), ('calendar_event', 'Календарное событие'), ('document', 'Документ'), ('request', 'Заявление'), ('procurement_request', 'Заявка на закупку'), ('employee', 'Сотрудник'), ('guest', 'Гость'), ('guest_visit', 'Заявка на гостевой визит'), ('attendance_record', 'Запись посещаемости'), ('external_link', 'Внешняя ссылка'), ('checklist_item', 'Пункт чек-листа')], max_length=32, verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Пункт')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_task_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Отметил выполненным')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа задачи',
                'verbose_name_plural': 'Пункты чек-листа задач',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['task', 'position'], name='tasks_taskc_task_id_0eaca5_idx'), models.Index(fields=['task', 'is_completed'], name='tasks_taskc_task_id_950de8_idx')],
            },
        ),
    ]
