# Generated by Django 5.2.4 on 2026-07-17 05:29

from django.db import migrations, models


def preserve_restricted_boards(apps, schema_editor):
    TaskBoard = apps.get_model("tasks", "TaskBoard")
    restricted_ids = TaskBoard.objects.filter(
        models.Q(members__isnull=False) | models.Q(departments__isnull=False)
    ).values_list("id", flat=True)
    TaskBoard.objects.filter(id__in=restricted_ids).update(access_scope="restricted")


def restore_legacy_access(apps, schema_editor):
    TaskBoard = apps.get_model("tasks", "TaskBoard")
    TaskBoard.objects.filter(access_scope="restricted").update(access_scope="all")


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0015_alter_taskactivity_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskboard",
            name="access_scope",
            field=models.CharField(
                choices=[
                    ("all", "Для всех"),
                    ("private", "Для себя"),
                    ("restricted", "Выборочно"),
                ],
                default="all",
                max_length=16,
                verbose_name="Доступ",
            ),
        ),
        migrations.RunPython(
            preserve_restricted_boards,
            restore_legacy_access,
        ),
    ]
