# Generated by Django 5.2.4 on 2026-07-17 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_payroll_run_reason_statement_public_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollstatementline",
            name="is_retro",
            field=models.BooleanField(
                default=False, verbose_name="Перерасчёт прошлого периода"
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("calculated", "Рассчитан"),
                    ("review", "На проверке"),
                    ("approved", "Утверждён"),
                    ("published", "Опубликован"),
                    ("returned", "Возвращён на исправление"),
                    ("superseded", "Заменён новой ревизией"),
                ],
                default="calculated",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("period",),
                name="pay_run_one_published_per_period",
            ),
        ),
    ]
