# Generated by Django 5.2.4 on 2026-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_payrollstatementline_is_retro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollworkrecord",
            name="reason",
            field=models.TextField(blank=True, verbose_name="Основание изменения"),
        ),
    ]
