# Generated by Django 5.2.4 on 2026-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_payrollworkrecord_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayrate",
            name="lock_version",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Версия черновика"
            ),
        ),
        migrations.AddField(
            model_name="payrollinputline",
            name="lock_version",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Версия черновика"
            ),
        ),
        migrations.AddField(
            model_name="payrollworkrecord",
            name="lock_version",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Версия черновика"
            ),
        ),
    ]
