# Generated by Django 5.2.4 on 2026-07-17 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_employeepayrate_lock_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollperiod",
            options={
                "ordering": ["-date_from", "-id"],
                "permissions": [
                    ("manage_payroll_inputs", "Может управлять данными для расчёта"),
                    ("approve_payroll_inputs", "Может утверждать данные для расчёта"),
                    ("calculate_payroll", "Может запускать расчёт зарплаты"),
                    ("approve_payroll", "Может утверждать расчёт зарплаты"),
                    (
                        "override_payroll_approval",
                        "Может самоутверждать данные и расчёты зарплаты",
                    ),
                    ("publish_payroll", "Может публиковать расчётные листки"),
                    ("view_all_payroll", "Может просматривать все расчёты"),
                    ("audit_payroll", "Может просматривать аудит расчётов"),
                ],
                "verbose_name": "Расчётный период",
                "verbose_name_plural": "Расчётные периоды",
            },
        ),
        migrations.RemoveConstraint(
            model_name="employeepayrate",
            name="pay_rate_maker_not_approver",
        ),
        migrations.RemoveConstraint(
            model_name="payrollinputline",
            name="pay_input_maker_not_approver",
        ),
        migrations.RemoveConstraint(
            model_name="payrollrun",
            name="pay_run_maker_not_approver",
        ),
        migrations.RemoveConstraint(
            model_name="payrollworkrecord",
            name="pay_work_maker_not_approver",
        ),
        migrations.AddField(
            model_name="employeepayrate",
            name="self_approval_overridden",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="Самоутверждение по особому праву",
            ),
        ),
        migrations.AddField(
            model_name="payrollinputline",
            name="self_approval_overridden",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="Самоутверждение по особому праву",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="self_approval_overridden",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="Самоутверждение по особому праву",
            ),
        ),
        migrations.AddField(
            model_name="payrollworkrecord",
            name="self_approval_overridden",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="Самоутверждение по особому праву",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeepayrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("created_by", models.F("approved_by")), _negated=True),
                    ("self_approval_overridden", True),
                    _connector="OR",
                ),
                name="pay_rate_maker_not_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeepayrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("self_approval_overridden", False),
                    models.Q(
                        ("approved_by__isnull", False),
                        ("created_by", models.F("approved_by")),
                    ),
                    _connector="OR",
                ),
                name="pay_rate_self_override_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollinputline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("created_by", models.F("approved_by")), _negated=True),
                    ("self_approval_overridden", True),
                    _connector="OR",
                ),
                name="pay_input_maker_not_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollinputline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("self_approval_overridden", False),
                    models.Q(
                        ("approved_by__isnull", False),
                        ("created_by", models.F("approved_by")),
                    ),
                    _connector="OR",
                ),
                name="pay_input_self_override_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("requested_by", models.F("approved_by")), _negated=True),
                    ("self_approval_overridden", True),
                    _connector="OR",
                ),
                name="pay_run_maker_not_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("self_approval_overridden", False),
                    models.Q(
                        ("approved_by__isnull", False),
                        ("requested_by", models.F("approved_by")),
                    ),
                    _connector="OR",
                ),
                name="pay_run_self_override_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollworkrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("created_by", models.F("approved_by")), _negated=True),
                    ("self_approval_overridden", True),
                    _connector="OR",
                ),
                name="pay_work_maker_not_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollworkrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("self_approval_overridden", False),
                    models.Q(
                        ("approved_by__isnull", False),
                        ("created_by", models.F("approved_by")),
                    ),
                    _connector="OR",
                ),
                name="pay_work_self_override_valid",
            ),
        ),
    ]
