# Generated by Django 5.2.4 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_alter_payrollperiod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeepayrate",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("excel", "Excel"),
                    ("api", "API"),
                    ("attendance", "Посещаемость"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="payrollinputline",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("excel", "Excel"),
                    ("api", "API"),
                    ("attendance", "Посещаемость"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="payrollworkrecord",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Вручную"),
                    ("excel", "Excel"),
                    ("api", "API"),
                    ("attendance", "Посещаемость"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
