# Generated by Django 5.2.4 on 2026-07-20 08:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_payrolldailyworkentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollWorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('daily_target_points', models.DecimalField(decimal_places=4, default=Decimal('5'), help_text='Единая дневная норма для всех сотрудников.', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Дневная норма баллов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки выработки',
                'verbose_name_plural': 'Настройки выработки',
            },
        ),
    ]
