# Generated by Django 5.2.4 on 2026-07-20 08:30

from django.db import migrations, models


def mark_daily_work_targets_as_automatic(apps, schema_editor):
    work_record = apps.get_model("finance", "PayrollWorkRecord")
    work_record.objects.filter(
        source="api",
        source_ref__startswith="daily-work:",
    ).update(target_points_overridden=False)


def mark_all_targets_as_overridden(apps, schema_editor):
    work_record = apps.get_model("finance", "PayrollWorkRecord")
    work_record.objects.update(target_points_overridden=True)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_payrollworksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworkrecord',
            name='target_points_overridden',
            field=models.BooleanField(default=True, editable=False, verbose_name='Норма указана вручную'),
        ),
        migrations.RunPython(
            mark_daily_work_targets_as_automatic,
            mark_all_targets_as_overridden,
        ),
    ]
