# Generated by Django 5.2.4 on 2026-07-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_payrollworkrecord_target_points_overridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollauditevent',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='finance.payrollperiod', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='payrolldailyworkentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_entries', to='finance.payrollperiod', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='payrollinputline',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_lines', to='finance.payrollperiod', verbose_name='Период выплаты'),
        ),
        migrations.AlterField(
            model_name='payrollinputline',
            name='relates_to_period',
            field=models.ForeignKey(blank=True, help_text='Заполняется для перерасчёта прошлого периода.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retro_input_lines', to='finance.payrollperiod', verbose_name='Относится к периоду'),
        ),
        migrations.AlterField(
            model_name='payrollinputline',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reversed_by', to='finance.payrollinputline', verbose_name='Сторнирует строку'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='finance.payrollperiod', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by_runs', to='finance.payrollrun', verbose_name='Пересчитывает ревизию'),
        ),
        migrations.AlterField(
            model_name='payrollstatement',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='finance.payrollrun', verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='payrollstatement',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by_statement', to='finance.payrollstatement', verbose_name='Заменяет листок'),
        ),
        migrations.AlterField(
            model_name='payrollstatementacknowledgement',
            name='statement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='finance.payrollstatement', verbose_name='Расчётный листок'),
        ),
        migrations.AlterField(
            model_name='payrollstatementline',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.payrollstatement', verbose_name='Расчётный листок'),
        ),
        migrations.AlterField(
            model_name='payrollworkrecord',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='finance.payrollperiod', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='payrollworkrecord',
            name='replaces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='replaced_by', to='finance.payrollworkrecord', verbose_name='Заменяет запись'),
        ),
    ]
