# Generated by Django 5.2.4 on 2026-04-21 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        ("employees", "0048_alter_employeeaction_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="effective_is_workday",
            field=models.BooleanField(
                default=True, verbose_name="Рабочий день с учетом кадрового состояния"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="personnel_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="employees.employeeaction",
                verbose_name="Кадровое событие",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="personnel_status",
            field=models.CharField(
                blank=True,
                default="normal",
                max_length=64,
                verbose_name="Кадровое состояние",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="personnel_status_label",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="Кадровое состояние для отображения",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["personnel_status"], name="attendance__personn_dbbd98_idx"
            ),
        ),
    ]
