# Generated by Codex on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendancerecord_effective_is_workday_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="is_manually_edited",
            field=models.BooleanField(default=False, verbose_name="Изменено вручную"),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="manual_edit_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Ручная корректировка",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="manual_edited_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время ручного изменения",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="manual_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_attendance_edits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Изменил вручную",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["is_manually_edited"],
                name="attendance__is_manu_07f532_idx",
            ),
        ),
    ]
