# Generated by Codex on 2026-04-22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_employeeworkschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardWorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(8, 0),
                        verbose_name="Начало рабочего дня",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=datetime.time(17, 0),
                        verbose_name="Конец рабочего дня",
                    ),
                ),
                (
                    "expected_hours",
                    models.FloatField(default=9, verbose_name="Норма часов"),
                ),
                (
                    "workdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Рабочие дни",
                    ),
                ),
                (
                    "date_overrides",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Календарные исключения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_standard_work_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стандартный график работы",
                "verbose_name_plural": "Стандартный график работы",
            },
        ),
    ]
