# Generated by Django on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):
    """
    Удаление старых таблиц calendar_app после миграции на django-scheduler.
    
    ВАЖНО: Перед применением этой миграции убедитесь, что:
    1. Все данные мигрированы в django-scheduler (таблицы schedule_*)
    2. Приложение schedule работает корректно
    3. Уведомления настроены в scheduling.notifications
    4. Есть резервная копия БД
    """

    initial = True

    dependencies = []

    operations = [
        # Это приложение не имеет моделей, только логика
        # Миграция создана чтобы Django не ругался
    ]
