# Generated by Django on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):
    """
    Удаление старых таблиц calendar_app после миграции на django-scheduler.

    ВАЖНО: Перед применением этой миграции убедитесь, что:
    1. Все данные мигрированы в django-scheduler (таблицы schedule_*)
    2. Приложение schedule работает корректно
    3. Уведомления настроены в scheduling.notifications
    4. Есть резервная копия БД
    """

    dependencies = [
        ('calendar_app', '0013_migrate_to_django_scheduler'),
    ]

    operations = [
        # Удаляем таблицы calendar_app
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS calendar_app_calendarevent CASCADE;",
                "DROP TABLE IF EXISTS calendar_app_calendarsubscription CASCADE;",
                "DROP TABLE IF EXISTS calendar_app_calendar CASCADE;",
            ],
            reverse_sql=[
                # Откат невозможен - данные удалены
                # Восстанавливать нужно из бэкапа
            ],
        ),
    ]
