# Generated by Django 5.2.4 on 2025-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0034_alter_employee_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Документ будет доступен всем сотрудникам выбранных отделов (включая будущих)', related_name='documents', to='employees.department', verbose_name='Отделы-получатели'),
        ),
    ]
