# Generated by Django 5.2.4 on 2025-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sent_to_all',
            field=models.BooleanField(default=True, help_text='Если включено — уведомление получат все активные сотрудники', verbose_name='Разослать всем'),
        ),
    ]
