# Generated by Django 5.2.4 on 2026-02-27 22:31

import django.db.models.deletion
import django_fsm
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_migrate_to_filer'),
        ('filer', '0018_alter_file_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Черновик'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрен'), ('published', 'Опубликован'), ('archived', 'Архивирован'), ('rejected', 'Отклонен')], default='draft', help_text='Текущее состояние документа в workflow', max_length=50, protected=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Файл, загруженный через django-filer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='filer.file', verbose_name='Файл'),
        ),
    ]
