# Generated by Django 5.2.4 on 2026-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_extended_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='acknowledgement_required',
            field=models.BooleanField(default=False, help_text='Если включено — сотрудники должны подтвердить ознакомление', verbose_name='Требуется ознакомление'),
        ),
    ]
