# Generated by Django 5.2.4 on 2026-03-05 12:37

from django.db import migrations, models


def migrate_status_to_is_published(apps, schema_editor):
    """
    Мигрирует старые FSM статусы в is_published boolean.

    Логика:
    - 'published' → is_published=True, published_at=uploaded_at
    - все остальные → is_published=False
    """
    Document = apps.get_model('documents', 'Document')

    # Опубликованные документы
    published_docs = Document.objects.filter(status='published')
    for doc in published_docs:
        doc.is_published = True
        doc.published_at = doc.uploaded_at  # Используем дату загрузки как дату публикации
        doc.save(update_fields=['is_published', 'published_at'])

    print(f"✅ Migrated {published_docs.count()} published documents")

    # Все остальные документы остаются с is_published=False (по умолчанию)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_related_documents_documentcomment'),
    ]

    operations = [
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Черновик (False) или Опубликован (True)', verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='document',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Когда документ был опубликован', null=True, verbose_name='Дата публикации'),
        ),
        # Затем мигрируем данные
        migrations.RunPython(migrate_status_to_is_published, reverse_code=migrations.RunPython.noop),
        # Затем удаляем старое поле
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
