# Generated by Django 5.2.4 on 2026-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_remove_fsm_add_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='document',
            name='published_at',
        ),
    ]
