# Generated by Django 5.2.4 on 2026-03-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
    ]
