# Generated by Django 5.2.4 on 2026-03-11 19:33

from django.db import migrations


def migrate_comments_forward(apps, schema_editor):
    """Миграция documents.DocumentComment → Communications.Message (SQL с threading)"""
    
    # 1. Создаем чаты для документов с комментариями
    schema_editor.execute("""
        INSERT INTO communications_chat (
            type, name, description, avatar, created_by_id, can_reply, flags,
            context_content_type_id, context_object_id,
            created_at, is_main, is_blocked, include_all_users, extra_data
        )
        SELECT DISTINCT
            'comments',
            'Комментарии: ' || substr(d.title, 1, 50),
            '',
            NULL,
            NULL::bigint,
            TRUE,
            '{"allow_replies": true, "allow_reactions": true, "allow_attachments": true, "allow_editing": true}'::jsonb,
            (SELECT id FROM django_content_type WHERE app_label='documents' AND model='document'),
            dc.document_id,
            NOW(),
            FALSE,
            FALSE,
            FALSE,
            '{}'::jsonb
        FROM documents_documentcomment dc
        JOIN documents_document d ON d.id = dc.document_id
        WHERE NOT EXISTS (
            SELECT 1 FROM communications_chat cc
            WHERE cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='documents' AND model='document')
            AND cc.context_object_id = dc.document_id
        )
    """)
    
    # 2. Переносим КОРНЕВЫЕ комментарии (parent IS NULL)
    schema_editor.execute("""
        INSERT INTO communications_message (
            chat_id, author_id, content, created_at,
            is_system, has_attachments,
            is_deleted, is_edited, edited_at,
            is_pinned, is_forwarded, is_cross_chat,
            system_metadata
        )
        SELECT 
            cc.id,
            dc.author_id,
            dc.text,
            dc.created_at,
            FALSE, FALSE, FALSE,
            dc.is_edited,
            CASE WHEN dc.is_edited THEN dc.updated_at ELSE NULL END,
            FALSE, FALSE, FALSE,
            jsonb_build_object(
                'legacy_comment_id', dc.id,
                'legacy_model', 'documents.DocumentComment'
            )
        FROM documents_documentcomment dc
        JOIN communications_chat cc ON (
            cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='documents' AND model='document')
            AND cc.context_object_id = dc.document_id
        )
        WHERE dc.parent_id IS NULL
        AND NOT EXISTS (
            SELECT 1 FROM communications_message m
            WHERE m.chat_id = cc.id
            AND m.author_id = dc.author_id
            AND m.created_at = dc.created_at
        )
    """)
    
    # 3. Переносим ОТВЕТЫ (parent IS NOT NULL) - с установкой reply_to и thread_root
    schema_editor.execute("""
        INSERT INTO communications_message (
            chat_id, author_id, content, created_at,
            is_system, has_attachments,
            is_deleted, is_edited, edited_at,
            is_pinned, is_forwarded, is_cross_chat,
            reply_to_id, thread_root_id,
            system_metadata
        )
        SELECT 
            cc.id,
            dc.author_id,
            dc.text,
            dc.created_at,
            FALSE, FALSE, FALSE,
            dc.is_edited,
            CASE WHEN dc.is_edited THEN dc.updated_at ELSE NULL END,
            FALSE, FALSE, FALSE,
            parent_msg.id,
            parent_msg.id,
            jsonb_build_object(
                'legacy_comment_id', dc.id,
                'legacy_model', 'documents.DocumentComment'
            )
        FROM documents_documentcomment dc
        JOIN communications_chat cc ON (
            cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='documents' AND model='document')
            AND cc.context_object_id = dc.document_id
        )
        JOIN communications_message parent_msg ON (
            parent_msg.chat_id = cc.id
            AND (parent_msg.system_metadata->>'legacy_comment_id')::bigint = dc.parent_id
        )
        WHERE dc.parent_id IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 FROM communications_message m
            WHERE m.chat_id = cc.id
            AND m.author_id = dc.author_id
            AND m.created_at = dc.created_at
        )
    """)


def migrate_comments_backward(apps, schema_editor):
    """Откат - удаляем чаты комментариев для документов"""
    schema_editor.execute("""
        DELETE FROM communications_chat
        WHERE type = 'comments'
        AND context_content_type_id = (
            SELECT id FROM django_content_type 
            WHERE app_label='documents' AND model='document'
        )
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_document_document_type'),
        ('communications', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_comments_forward,
            migrate_comments_backward
        ),
    ]
