# Generated by Django 5.2.4 on 2026-03-11 19:33

from django.db import migrations
from django.utils import timezone


def migrate_comments_forward(apps, schema_editor):
    """Миграция documents.DocumentComment → Communications.Message (ORM с threading)"""

    Chat = apps.get_model('communications', 'Chat')
    Message = apps.get_model('communications', 'Message')
    DocumentComment = apps.get_model('documents', 'DocumentComment')
    Document = apps.get_model('documents', 'Document')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        doc_ct = ContentType.objects.get(app_label='documents', model='document')
    except ContentType.DoesNotExist:
        return

    # 1. Создаем чаты для документов с комментариями
    doc_ids_with_comments = DocumentComment.objects.values_list('document_id', flat=True).distinct()

    for doc_id in doc_ids_with_comments:
        if Chat.objects.filter(
            type='comments',
            context_content_type=doc_ct,
            context_object_id=doc_id
        ).exists():
            continue

        try:
            doc = Document.objects.get(id=doc_id)
            chat_name = f"Комментарии: {doc.title[:50]}" if hasattr(doc, 'title') and doc.title else "Комментарии"
        except Document.DoesNotExist:
            chat_name = "Комментарии"

        Chat.objects.create(
            type='comments',
            name=chat_name,
            description='',
            avatar=None,
            created_by=None,
            can_reply=True,
            flags={'allow_replies': True, 'allow_reactions': True, 'allow_attachments': True, 'allow_editing': True},
            context_content_type=doc_ct,
            context_object_id=doc_id,
            created_at=timezone.now(),
            is_main=False,
            is_blocked=False,
            include_all_users=False,
            extra_data={}
        )

    # 2. Переносим КОРНЕВЫЕ комментарии (parent IS NULL)
    root_comments = DocumentComment.objects.filter(parent__isnull=True).select_related('author', 'document')

    for comment in root_comments:
        try:
            chat = Chat.objects.get(
                type='comments',
                context_content_type=doc_ct,
                context_object_id=comment.document_id
            )
        except Chat.DoesNotExist:
            continue

        if Message.objects.filter(
            chat=chat,
            author_id=comment.author_id,
            created_at=comment.created_at
        ).exists():
            continue

        Message.objects.create(
            chat=chat,
            author_id=comment.author_id,
            content=comment.text or '',
            created_at=comment.created_at,
            is_system=False,
            has_attachments=False,
            is_deleted=False,
            is_edited=comment.is_edited if hasattr(comment, 'is_edited') else False,
            edited_at=comment.updated_at if (hasattr(comment, 'is_edited') and comment.is_edited and hasattr(comment, 'updated_at')) else None,
            is_pinned=False,
            is_forwarded=False,
            is_cross_chat=False,
            system_type='',
            system_metadata={
                'legacy_comment_id': comment.id,
                'legacy_model': 'documents.DocumentComment'
            }
        )

    # 3. Переносим ОТВЕТЫ (parent IS NOT NULL) - с установкой reply_to и thread_root
    reply_comments = DocumentComment.objects.filter(parent__isnull=False).select_related('author', 'document', 'parent')

    for comment in reply_comments:
        try:
            chat = Chat.objects.get(
                type='comments',
                context_content_type=doc_ct,
                context_object_id=comment.document_id
            )
        except Chat.DoesNotExist:
            continue

        if Message.objects.filter(
            chat=chat,
            author_id=comment.author_id,
            created_at=comment.created_at
        ).exists():
            continue

        # Находим родительское сообщение
        try:
            parent_msg = Message.objects.get(
                chat=chat,
                system_metadata__legacy_comment_id=comment.parent_id
            )
        except Message.DoesNotExist:
            continue

        Message.objects.create(
            chat=chat,
            author_id=comment.author_id,
            content=comment.text or '',
            created_at=comment.created_at,
            is_system=False,
            has_attachments=False,
            is_deleted=False,
            is_edited=comment.is_edited if hasattr(comment, 'is_edited') else False,
            edited_at=comment.updated_at if (hasattr(comment, 'is_edited') and comment.is_edited and hasattr(comment, 'updated_at')) else None,
            is_pinned=False,
            is_forwarded=False,
            is_cross_chat=False,
            reply_to=parent_msg,
            thread_root=parent_msg,
            system_type='',
            system_metadata={
                'legacy_comment_id': comment.id,
                'legacy_model': 'documents.DocumentComment'
            }
        )


def migrate_comments_backward(apps, schema_editor):
    """Откат - удаляем чаты комментариев для документов"""
    Chat = apps.get_model('communications', 'Chat')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        doc_ct = ContentType.objects.get(app_label='documents', model='document')
        Chat.objects.filter(
            type='comments',
            context_content_type=doc_ct
        ).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_document_document_type'),
        ('communications', '0037_remove_department_type'),  # Зафиксировали конкретную версию
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_comments_forward,
            migrate_comments_backward
        ),
    ]
