# Generated by Django 5.2.4 on 2026-03-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_migrate_comments_to_communications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentComment',
        ),
    ]
