# Generated by Django 5.2.4 on 2025-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_skill_remove_employee_position_employee_wechat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sms_activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
