# Generated by Django 5.2.4 on 2025-08-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_sms_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, verbose_name='WeChat'),
        ),
    ]
