# Generated by Django 5.2.4 on 2025-08-07 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_department_options_employeedepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={'verbose_name': 'Принадлежность к отделу', 'verbose_name_plural': 'Принадлежности к отделам'},
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedepartment', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedepartment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employeedepartment',
            unique_together={('employee', 'department', 'date_from')},
        ),
    ]
