# Generated by Django 5.2.4 on 2025-08-07 12:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeedepartment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'verbose_name': 'Employee absence', 'verbose_name_plural': 'Employee absences'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeaction',
            options={'ordering': ['-date'], 'verbose_name': 'Personnel action', 'verbose_name_plural': 'Personnel actions'},
        ),
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={'verbose_name': 'Membership in department', 'verbose_name_plural': 'Memberships in departments'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'verbose_name': 'Employee position', 'verbose_name_plural': 'Employee positions'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_from',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_to',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick leave'), ('other', 'Other')], max_length=32, verbose_name='Absence type'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Department head'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Department name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(verbose_name='Graduation year'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский'), (0, 'Не указан')], default=0, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=100, region=None, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sms_activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='SMS activation code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='action',
            field=models.CharField(choices=[('hired', 'Принят'), ('dismissed', 'Уволен'), ('on_leave', 'В отпуске'), ('returned_from_leave', 'Вернулся из отпуска'), ('on_maternity', 'В декрете'), ('returned_from_maternity', 'Вернулся из декрета'), ('transferred', 'Переведен'), ('rehired', 'Восстановлен')], max_length=32, verbose_name='Personnel action'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment / Reason'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='date',
            field=models.DateTimeField(verbose_name='Action date'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Date from'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Date to'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedepartment', to='employees.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedepartment', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Role in department'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='date_from',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Position title'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Skill name'),
        ),
    ]
