# Generated by Django 5.2.4 on 2025-08-07 12:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_absence_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'verbose_name': 'Отсутствие сотрудника', 'verbose_name_plural': 'Отсутствия сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeaction',
            options={'ordering': ['-date'], 'verbose_name': 'Кадровое событие', 'verbose_name_plural': 'Кадровые события'},
        ),
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={'verbose_name': 'Принадлежность к отделу', 'verbose_name_plural': 'Принадлежности к отделам'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'verbose_name': 'Должность сотрудника', 'verbose_name_plural': 'Должности сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_from',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_to',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.CharField(choices=[('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('other', 'Другое')], max_length=32, verbose_name='Тип отсутствия'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский'), (0, 'Не указан')], default=0, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=100, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.skill'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sms_activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='action',
            field=models.CharField(choices=[('hired', 'Принят'), ('dismissed', 'Уволен'), ('on_leave', 'В отпуске'), ('returned_from_leave', 'Вернулся из отпуска'), ('on_maternity', 'В декрете'), ('returned_from_maternity', 'Вернулся из декрета'), ('transferred', 'Переведен'), ('rehired', 'Восстановлен')], max_length=32, verbose_name='Кадровое событие'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий/причина'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='date',
            field=models.DateTimeField(verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedepartment', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedepartment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='date_from',
            field=models.DateField(verbose_name='Дата начала должности'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания должности'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
