# Generated by Django 5.2.4 on 2025-08-08 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_absence_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedepartment',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Роль в отделе'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department'),
        ),
    ]
