# Generated by Django 5.2.4 on 2025-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_historicalemployeeaction_historicalemployeeposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_appointed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата назначения руководителя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтверждён'),
        ),
        migrations.AlterField(
            model_name='employeeaction',
            name='action',
            field=models.CharField(choices=[('hired', 'Принят'), ('dismissed', 'Уволен'), ('on_leave', 'В отпуске'), ('returned_from_leave', 'Вернулся из отпуска'), ('on_maternity', 'В декрете'), ('returned_from_maternity', 'Вернулся из декрета'), ('transferred', 'Переведен'), ('rehired', 'Восстановлен')], max_length=50, verbose_name='Кадровое событие'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeaction',
            name='action',
            field=models.CharField(choices=[('hired', 'Принят'), ('dismissed', 'Уволен'), ('on_leave', 'В отпуске'), ('returned_from_leave', 'Вернулся из отпуска'), ('on_maternity', 'В декрете'), ('returned_from_maternity', 'Вернулся из декрета'), ('transferred', 'Переведен'), ('rehired', 'Восстановлен')], max_length=50, verbose_name='Кадровое событие'),
        ),
        migrations.AlterUniqueTogether(
            name='employeedepartment',
            unique_together={('employee', 'department')},
        ),
    ]
