# Generated by Django 5.2.4 on 2025-08-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0011_department_head_appointed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employeedepartment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeposition',
            name='department',
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='employees.department')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.AlterField(
            model_name='employeedepartment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='employees.departmentrole'),
        ),
        migrations.AddIndex(
            model_name='employeedepartment',
            index=models.Index(fields=['department', 'is_active'], name='employees_e_departm_40dcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartment',
            index=models.Index(fields=['employee', 'is_active'], name='employees_e_employe_e4fe19_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeedepartment',
            constraint=models.UniqueConstraint(fields=('employee', 'department'), name='uniq_employee_department'),
        ),
        migrations.AddField(
            model_name='positionrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='position_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_positions', to='employees.positionrole'),
        ),
        migrations.AddField(
            model_name='historicalemployeeposition',
            name='position_role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.positionrole'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['employee'], name='employees_e_employe_720802_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['date_from', 'date_to'], name='employees_e_date_fr_599bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentrole',
            unique_together={('department', 'name')},
        ),
    ]
