# Generated by Django 5.2.4 on 2025-08-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0013_alter_employeeposition_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionrole',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeposition',
            name='position_role',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='position_role',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_permissions', to='auth.group', verbose_name='Группа прав (по должности)'),
        ),
        migrations.AddField(
            model_name='historicalemployeeposition',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group', verbose_name='Группа прав (по должности)'),
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='PositionRole',
        ),
    ]
