# Generated by Django 5.2.4 on 2025-08-21 13:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0014_remove_positionrole_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalemployeeposition',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeposition',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeposition',
            name='history_user',
        ),
        migrations.CreateModel(
            name='HistoricalPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Должность',
                'verbose_name_plural': 'historical Должности',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('groups', models.ManyToManyField(blank=True, related_name='positions', to='auth.group', verbose_name='Группы прав')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='EmployeePosition',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployeePosition',
        ),
    ]
