# Generated by Django 5.2.4 on 2025-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_remove_historicalemployeeposition_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('change_department_head', 'Can change department head'), ('assign_department_role', 'Can assign role within department'), ('manage_department', 'Can manage department')], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='departmentrole',
            options={'verbose_name': 'Роль в отделе', 'verbose_name_plural': 'Роли в отделе'},
        ),
        migrations.AlterField(
            model_name='department',
            name='head_appointed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения руководителя'),
        ),
    ]
