# Generated by Django 5.2.4 on 2025-08-25 11:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0016_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='employee_email_lower_idx'),
        ),
    ]
