# Generated by Django 5.2.4 on 2025-08-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_employee_email_lower_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'permissions': [('assign_position_groups', 'Can assign auth groups to positions')], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
