# Generated by Django 5.2.4 on 2025-08-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_position_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
