# Generated by Django 5.2.4 on 2025-08-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name'), 'permissions': [('manage_employee_skills', 'Может управлять навыками сотрудников')], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
