# Generated by Django 5.2.4 on 2025-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('manage_department', 'Управлять отделом'), ('change_department_head', 'Назначать руководителя'), ('assign_department_role', 'Назначать роли участникам')], max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='departmentrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='scoped_permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='employees.departmentpermission'),
        ),
    ]
