# Generated by Django 5.2.4 on 2025-09-03 12:02

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_departmentpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentrole',
            options={'ordering': ('name', 'department', 'id'), 'verbose_name': 'Роль в отделе', 'verbose_name_plural': 'Роли в отделе'},
        ),
        migrations.RemoveConstraint(
            model_name='employeedepartment',
            name='uniq_employee_department',
        ),
        migrations.RemoveIndex(
            model_name='employeedepartment',
            name='employees_e_departm_40dcd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeedepartment',
            name='employees_e_employe_e4fe19_idx',
        ),
        migrations.AddIndex(
            model_name='employeedepartment',
            index=models.Index(fields=['department_id', 'is_active', 'employee_id'], name='employees_e_departm_81ade2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartment',
            index=models.Index(fields=['employee_id', 'department_id'], name='employees_e_employe_b4b0e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeedepartment',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('department_id', 'employee_id'), name='uniq_employee_per_department'),
        ),
    ]
