# Generated by Django 5.2.4 on 2025-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_departmentrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpermission',
            name='code',
            field=models.CharField(choices=[('manage_department', 'Управлять отделом'), ('change_department_head', 'Назначать руководителя'), ('assign_department_role', 'Назначать роли участникам'), ('manage_department_events', 'Управлять календарём отдела')], max_length=64, unique=True),
        ),
    ]
