# Generated by Django 5.2.4 on 2025-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_alter_departmentpermission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_ldap_modify_ts',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='LDAP modify ts'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_ldap_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя успешная запись в LDAP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ldap_dn',
            field=models.CharField(blank=True, help_text='Текущий DN записи в каталоге (для отладки/трассировки).', max_length=512, null=True, verbose_name='LDAP DN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ldap_guid',
            field=models.CharField(blank=True, help_text='Устойчивый ID из LDAP (entryUUID/objectGUID в hex/строке).', max_length=64, null=True, unique=True, verbose_name='LDAP GUID'),
        ),
    ]
