# Generated by Django 5.2.4 on 2025-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_employee_last_ldap_modify_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_ldap_managed',
            field=models.BooleanField(default=False, verbose_name='Управляется LDAP'),
        ),
    ]
