# Generated by Django 5.2.4 on 2025-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_employee_is_ldap_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=32)),
                ('object_pk', models.CharField(db_index=True, max_length=64)),
                ('ldap_dn', models.TextField(blank=True, default='')),
                ('ldap_guid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('last_ldap_modify_ts', models.DateTimeField(blank=True, null=True)),
                ('last_django_modify_ts', models.DateTimeField(blank=True, null=True)),
                ('last_sync_dir', models.CharField(default='ldap', max_length=8)),
                ('data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние синхронизации LDAP',
                'verbose_name_plural': 'Состояния синхронизации LDAP',
                'unique_together': {('model', 'object_pk')},
            },
        ),
    ]
