# Generated by Django 5.2.4 on 2025-10-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_ldapsyncstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_ldap_modify_ts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_ldap_sync_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ldap_dn',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ldap_guid',
        ),
    ]
