# Generated by Django 5.2.4 on 2025-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_remove_employee_last_ldap_modify_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ldap_group_dn',
            field=models.CharField(blank=True, default='', help_text='Напр.: CN=DEP_it,OU=Department,OU=company,DC=robotail,DC=local', max_length=512, verbose_name='DN агрегаторной группы отдела в AD (DEP_*)'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='ldap_group_dn',
            field=models.CharField(blank=True, default='', help_text='Напр.: CN=ROLE_it__oncall,OU=Role,OU=company,DC=robotail,DC=local', max_length=512, verbose_name='DN агрегаторной группы роли в AD (ROLE_*)'),
        ),
        migrations.AddField(
            model_name='historicalposition',
            name='ldap_group_dn',
            field=models.CharField(blank=True, default='', help_text='Напр.: CN=POS_engineer,OU=Position,OU=company,DC=robotail,DC=local', max_length=512, verbose_name='DN агрегаторной группы должности в AD (POS_*)'),
        ),
        migrations.AddField(
            model_name='position',
            name='ldap_group_dn',
            field=models.CharField(blank=True, default='', help_text='Напр.: CN=POS_engineer,OU=Position,OU=company,DC=robotail,DC=local', max_length=512, verbose_name='DN агрегаторной группы должности в AD (POS_*)'),
        ),
    ]
