# Generated by Django 5.2.4 on 2025-10-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_department_ldap_group_dn_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeedepartment',
            name='uniq_employee_per_department',
        ),
        migrations.AlterField(
            model_name='departmentpermission',
            name='code',
            field=models.CharField(choices=[('manage_department', 'Управлять отделом'), ('change_department_head', 'Назначать руководителя'), ('assign_department_role', 'Назначать роли участникам'), ('manage_department_events', 'Управлять календарём отдела'), ('publish_department_post', 'Публиковать новости на странице отдела'), ('manage_department_feed', 'Редактировать публикации отдела'), ('view_requestcomment', 'Просмотр комментариев по заявлениям'), ('add_requestcomment', 'Добавление коментариев по заявлениям'), ('view_request', 'Просмотр заявлений отдела'), ('can_process_requests', 'Рассмотрение заявлений отдела')], max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='employeedepartment',
            constraint=models.UniqueConstraint(fields=('employee_id',), name='uniq_department_per_employee'),
        ),
    ]
