# Generated by Django 5.2.4 on 2025-10-21 05:06

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_remove_employeedepartment_uniq_employee_per_department_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeedepartment',
            name='uniq_department_per_employee',
        ),
        migrations.AddConstraint(
            model_name='employeedepartment',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('department_id', 'employee_id'), name='uniq_employee_per_department'),
        ),
    ]
