# Generated by Django 5.2.4 on 2025-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_remove_employeedepartment_uniq_department_per_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ваш Telegram Chat ID для получения уведомлений (найдите через @userinfobot)', max_length=100, verbose_name='Telegram Chat ID'),
        ),
    ]
