# Generated by Django 5.2.4 on 2025-12-09 12:56

from django.db import migrations


def add_manage_equipment_permission(apps, schema_editor):
    """Добавляет скоуп-право для управления оборудованием отдела."""
    DepartmentPermission = apps.get_model('employees', 'DepartmentPermission')
    DepartmentPermission.objects.get_or_create(
        code='manage_department_equipment',
        defaults={'name': 'Управлять оборудованием отдела'}
    )


def remove_manage_equipment_permission(apps, schema_editor):
    """Удаляет скоуп-право."""
    DepartmentPermission = apps.get_model('employees', 'DepartmentPermission')
    DepartmentPermission.objects.filter(
        code='manage_department_equipment'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_alter_employee_telegram'),
    ]

    operations = [
        migrations.RunPython(
            add_manage_equipment_permission,
            remove_manage_equipment_permission,
        ),
    ]
