# Generated by Django migration script
# employees/migrations/0036_migrate_role_assignments.py

from django.db import migrations


def migrate_role_data(apps, schema_editor):
    """Переносит назначения ролей из EmployeeDepartment.role в RoleAssignment."""
    EmployeeDepartment = apps.get_model('employees', 'EmployeeDepartment')
    RoleAssignment = apps.get_model('employees', 'RoleAssignment')

    # Находим все связи с назначенными ролями
    links_with_roles = EmployeeDepartment.objects.filter(
        role__isnull=False
    ).select_related('employee', 'role')

    created_count = 0
    for link in links_with_roles:
        # Создаём RoleAssignment если ещё нет
        assignment, created = RoleAssignment.objects.get_or_create(
            employee=link.employee,
            role=link.role,
            defaults={
                'is_active': link.is_active,
                'assigned_by': None,  # Исторические данные без информации о назначителе
            }
        )
        if created:
            created_count += 1

    if created_count > 0:
        print(f"Migrated {created_count} role assignments from EmployeeDepartment to RoleAssignment")


def reverse_migration(apps, schema_editor):
    """Откат: удаляем все RoleAssignment (данные сохранены в EmployeeDepartment.role)."""
    RoleAssignment = apps.get_model('employees', 'RoleAssignment')
    RoleAssignment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_create_role_assignment'),
    ]

    operations = [
        migrations.RunPython(migrate_role_data, reverse_migration),
    ]
