# Generated by Django 5.2.4 on 2026-02-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_migrate_role_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name'), 'permissions': [('manage_employee_skills', 'Может управлять навыками сотрудников'), ('view_ldap_info', 'Может просматривать LDAP информацию сотрудников')], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
