# Generated by Django 5.2.4 on 2026-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, help_text='Кэшированный LDAP логин сотрудника', max_length=150, null=True, verbose_name='LDAP Username (кэш)'),
        ),
    ]
