# Generated by Django 5.2.4 on 2026-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0038_employee_username'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['username'], name='employees_e_usernam_4d3ddc_idx'),
        ),
    ]
