# Generated by Django 5.2.4 on 2026-02-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_add_manage_equipment_permission'),
        ('employees', '0039_employee_employees_e_usernam_4d3ddc_idx'),
    ]

    operations = [
    ]
