# Generated by Django 5.2.4 on 2026-03-19 07:45

import ldapdb.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_alter_departmentpermission_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapGroup',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('object_guid', ldapdb.models.fields.CharField(db_column='objectGUID', max_length=200)),
                ('sam_account_name', ldapdb.models.fields.CharField(db_column='sAMAccountName', max_length=200)),
                ('description', ldapdb.models.fields.CharField(blank=True, db_column='description', max_length=200)),
                ('member', ldapdb.models.fields.ListField(blank=True, db_column='member')),
                ('member_of', ldapdb.models.fields.ListField(blank=True, db_column='memberOf')),
                ('when_created', ldapdb.models.fields.DateTimeField(db_column='whenCreated')),
                ('when_changed', ldapdb.models.fields.DateTimeField(db_column='whenChanged')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LdapOrganizationalUnit',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ou', ldapdb.models.fields.CharField(db_column='ou', max_length=200)),
                ('object_guid', ldapdb.models.fields.CharField(db_column='objectGUID', max_length=200)),
                ('description', ldapdb.models.fields.CharField(blank=True, db_column='description', max_length=200)),
                ('managed_by', ldapdb.models.fields.CharField(blank=True, db_column='managedBy', max_length=200)),
                ('when_created', ldapdb.models.fields.DateTimeField(db_column='whenCreated')),
                ('when_changed', ldapdb.models.fields.DateTimeField(db_column='whenChanged')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LdapUser',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('object_guid', ldapdb.models.fields.CharField(db_column='objectGUID', max_length=200)),
                ('sam_account_name', ldapdb.models.fields.CharField(db_column='sAMAccountName', max_length=200)),
                ('user_principal_name', ldapdb.models.fields.CharField(db_column='userPrincipalName', max_length=200)),
                ('given_name', ldapdb.models.fields.CharField(db_column='givenName', max_length=200)),
                ('sn', ldapdb.models.fields.CharField(db_column='sn', max_length=200)),
                ('display_name', ldapdb.models.fields.CharField(db_column='displayName', max_length=200)),
                ('mail', ldapdb.models.fields.CharField(db_column='mail', max_length=200)),
                ('telephone_number', ldapdb.models.fields.CharField(blank=True, db_column='telephoneNumber', max_length=200)),
                ('mobile', ldapdb.models.fields.CharField(blank=True, db_column='mobile', max_length=200)),
                ('user_account_control', ldapdb.models.fields.IntegerField(db_column='userAccountControl')),
                ('description', ldapdb.models.fields.CharField(blank=True, db_column='description', max_length=200)),
                ('thumbnail_photo', ldapdb.models.fields.ImageField(blank=True, db_column='thumbnailPhoto')),
                ('employee_number', ldapdb.models.fields.CharField(blank=True, db_column='employeeNumber', max_length=200)),
                ('member_of', ldapdb.models.fields.ListField(blank=True, db_column='memberOf')),
                ('when_created', ldapdb.models.fields.DateTimeField(db_column='whenCreated')),
                ('when_changed', ldapdb.models.fields.DateTimeField(db_column='whenChanged')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
