# Generated by Django 5.2.4 on 2026-03-27 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_ldapsyncqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('scope', models.CharField(choices=[('company', 'Компания'), ('department', 'Отдел')], default='company', max_length=20, verbose_name='Область действия')),
                ('level', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Чем выше число, тем выше уровень эскалации.', verbose_name='Уровень согласования')),
                ('resolution_strategy', models.CharField(choices=[('assignment', 'По явному назначению'), ('department_head', 'По руководителю отдела')], default='assignment', max_length=20, verbose_name='Стратегия определения согласующего')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('position', models.ForeignKey(blank=True, help_text='Опционально: используется как fallback, если нет активного назначения.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_authorities', to='employees.position', verbose_name='Базовая должность')),
            ],
            options={
                'verbose_name': 'Роль согласования',
                'verbose_name_plural': 'Роли согласования',
                'ordering': ('level', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalAuthorityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Меньшее значение имеет более высокий приоритет.', verbose_name='Приоритет')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='Основное назначение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_authorities', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.approvalauthority', verbose_name='Роль согласования')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_authority_assignments', to='employees.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_authority_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение роли согласования',
                'verbose_name_plural': 'Назначения ролей согласования',
                'ordering': ('authority', 'department', '-is_primary', 'priority', 'id'),
                'indexes': [models.Index(fields=['authority', 'is_active', 'department'], name='employees_a_authori_a9c9f4_idx'), models.Index(fields=['employee', 'is_active'], name='employees_a_employe_5199d0_idx'), models.Index(fields=['authority', 'department', 'priority'], name='employees_a_authori_1883a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('authority', 'employee', 'department'), name='uniq_approval_authority_assignment')],
            },
        ),
    ]
