# Generated by Django 5.2.4 on 2026-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_ldapgroup_ldaporganizationalunit_ldapuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, help_text='Имя операции (employee_save, department_delete, group_m2m и т.д.)', max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=32)),
                ('object_pk', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='JSON с аргументами для повтора операции')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка (исчерпаны попытки)')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Очередь LDAP синхронизации',
                'verbose_name_plural': 'Очередь LDAP синхронизации',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='ldap_queue_retry_idx')],
            },
        ),
    ]
