# Generated by Django 5.2.4 on 2026-03-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_ldaporganizationalunitgroup_approvalauthority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalAuthorityAssignment',
        ),
        migrations.DeleteModel(
            name='ApprovalAuthority',
        ),
    ]
