# Generated by Django 5.2.4 on 2026-03-29 23:58

import employees.ldap.mixins
import ldapdb.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_remove_approval_authority_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapOrganizationalUnitGroup',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', max_length=200)),
                ('sam_account_name', ldapdb.models.fields.CharField(db_column='sAMAccountName', max_length=200)),
                ('description', ldapdb.models.fields.CharField(blank=True, db_column='description', max_length=200)),
                ('member', ldapdb.models.fields.ListField(blank=True, db_column='member')),
                ('member_of', ldapdb.models.fields.ListField(blank=True, db_column='memberOf')),
                ('when_created', ldapdb.models.fields.DateTimeField(db_column='whenCreated')),
                ('when_changed', ldapdb.models.fields.DateTimeField(db_column='whenChanged')),
            ],
            options={
                'managed': False,
            },
            bases=(employees.ldap.mixins.ModifyDnMixin, models.Model),
        ),
    ]
