# Generated by Django 5.2.4 on 2026-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_ldaporganizationalunitgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapsyncqueue',
            name='operation',
            field=models.CharField(db_index=True, help_text='Имя операции: employee_save, department_delete, group_m2m и т.д.', max_length=64),
        ),
    ]
