# Generated by Django 5.2.4 on 2026-04-16 11:09

from django.db import migrations, models


def remove_obsolete_department_permissions(apps, schema_editor):
    DepartmentPermission = apps.get_model("employees", "DepartmentPermission")
    DepartmentPermission.objects.filter(
        code__in=["manage_department_events", "publish_department_post"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0046_alter_ldapsyncqueue_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpermission',
            name='code',
            field=models.CharField(choices=[('manage_department', 'Управлять отделом'), ('change_department_head', 'Назначать руководителя'), ('assign_department_role', 'Назначать роли участникам'), ('manage_department_feed', 'Редактировать публикации отдела'), ('view_requestcomment', 'Просмотр комментариев по заявлениям'), ('add_requestcomment', 'Добавление коментариев по заявлениям'), ('view_request', 'Просмотр заявлений отдела'), ('can_process_requests', 'Рассмотрение заявлений отдела'), ('manage_department_equipment', 'Управлять оборудованием отдела')], max_length=64, unique=True),
        ),
        migrations.RunPython(
            remove_obsolete_department_permissions,
            migrations.RunPython.noop,
        ),
    ]
