# Generated by Django 5.2.4 on 2026-04-22 10:52

import django.db.models.deletion
from django.db import migrations, models


def backfill_source_request_and_remove_duplicates(apps, schema_editor):
    EmployeeAction = apps.get_model("employees", "EmployeeAction")
    Request = apps.get_model("requests_app", "Request")

    request_ids = set()
    for action in EmployeeAction.objects.exclude(extra__isnull=True).only(
        "id",
        "extra",
    ):
        if isinstance(action.extra, dict) and action.extra.get("request_id"):
            request_ids.add(action.extra["request_id"])

    existing_request_ids = set(
        Request.objects.filter(id__in=request_ids).values_list("id", flat=True)
    )

    for action in EmployeeAction.objects.exclude(extra__isnull=True).only(
        "id",
        "extra",
        "source_request_id",
    ):
        if action.source_request_id:
            continue
        if not isinstance(action.extra, dict):
            continue
        request_id = action.extra.get("request_id")
        if request_id in existing_request_ids:
            action.source_request_id = request_id
            action.save(update_fields=["source_request"])

    from django.db.models import Count, Min

    duplicate_groups = (
        EmployeeAction.objects.filter(source_request__isnull=False)
        .values("source_request_id", "action")
        .annotate(first_id=Min("id"), action_count=Count("id"))
        .filter(action_count__gt=1)
    )

    for group in duplicate_groups:
        (
            EmployeeAction.objects.filter(
                source_request_id=group["source_request_id"],
                action=group["action"],
            )
            .exclude(id=group["first_id"])
            .delete()
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0048_alter_employeeaction_action_and_more"),
        ("requests_app", "0011_remove_requestcomment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeaction",
            name="source_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_actions",
                to="requests_app.request",
                verbose_name="Источник-заявление",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployeeaction",
            name="source_request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="requests_app.request",
                verbose_name="Источник-заявление",
            ),
        ),
        migrations.RunPython(
            backfill_source_request_and_remove_duplicates,
            reverse_code=noop_reverse,
        ),
        migrations.AddConstraint(
            model_name="employeeaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_request__isnull", False)),
                fields=("source_request", "action"),
                name="uniq_employee_action_source_request_action",
            ),
        ),
    ]
