# Generated by Codex on 2026-04-28

from datetime import timedelta

from django.db import migrations, models


TEMPORARY_ACTION_RETURN_MAP = {
    "on_leave": "returned_from_leave",
    "on_sick_leave": "returned_from_sick_leave",
    "on_day_off": "returned_from_day_off",
    "on_maternity": "returned_from_maternity",
}

ACTION_CHOICES = [
    ("working", "Работает"),
    ("remote", "На удалёнке"),
    ("hired", "Принят"),
    ("dismissed", "Уволен"),
    ("on_leave", "В отпуске"),
    ("returned_from_leave", "Вернулся из отпуска"),
    ("on_sick_leave", "На больничном"),
    ("returned_from_sick_leave", "Вернулся с больничного"),
    ("on_day_off", "В отгуле"),
    ("returned_from_day_off", "Вернулся из отгула"),
    ("on_maternity", "В декрете"),
    ("returned_from_maternity", "Вернулся из декрета"),
    ("transferred", "Переведен"),
    ("rehired", "Восстановлен"),
]


def backfill_date_to(apps, schema_editor):
    EmployeeAction = apps.get_model("employees", "EmployeeAction")

    for action in (
        EmployeeAction.objects.filter(
            action__in=TEMPORARY_ACTION_RETURN_MAP.keys(),
            date_to__isnull=True,
        )
        .select_related("source_request")
        .order_by("employee_id", "date", "id")
    ):
        date_to = None
        if action.source_request_id and action.source_request.date_to:
            date_to = action.source_request.date_to
        else:
            return_action = _find_return_action(EmployeeAction, action)
            if return_action and return_action.date:
                date_to = return_action.date.date() - timedelta(days=1)

        if date_to is not None:
            action.date_to = date_to
            action.save(update_fields=["date_to"])


def _find_return_action(EmployeeAction, action):
    return_action = TEMPORARY_ACTION_RETURN_MAP[action.action]
    qs = EmployeeAction.objects.filter(
        employee_id=action.employee_id,
        action=return_action,
        date__gte=action.date,
    )
    if action.source_request_id:
        matched = (
            qs.filter(source_request_id=action.source_request_id)
            .order_by("date", "id")
            .first()
        )
        if matched:
            return matched
    return qs.order_by("date", "id").first()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0049_employeeaction_source_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeaction",
            name="date_to",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата окончания временного события",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployeeaction",
            name="date_to",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата окончания временного события",
            ),
        ),
        migrations.AlterField(
            model_name="employeeaction",
            name="action",
            field=models.CharField(
                choices=ACTION_CHOICES,
                max_length=50,
                verbose_name="Кадровое событие",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployeeaction",
            name="action",
            field=models.CharField(
                choices=ACTION_CHOICES,
                max_length=50,
                verbose_name="Кадровое событие",
            ),
        ),
        migrations.RunPython(backfill_date_to, reverse_code=noop_reverse),
    ]
