from django.urls import path

from .views import (
    OwnPayrollStatementAcknowledgeView,
    OwnPayrollStatementDetailView,
    OwnPayrollStatementListView,
    OwnPayrollWorkRecordView,
)
from .admin_views import (
    EmployeePayRateApproveView,
    EmployeePayRateDetailView,
    EmployeePayRateListCreateView,
    EmployeePayRateReviseView,
    PayrollBulkPayRateView,
    PayrollBulkPointRateView,
    PayrollAdminComponentListView,
    PayrollAdminEmployeeListView,
    PayrollAdminPeriodDetailView,
    PayrollAdminPeriodListCreateView,
    PayrollAdminWorkspaceView,
    PayrollAttendanceWorkRecordsView,
    PayrollInputLineApproveView,
    PayrollInputLineDetailView,
    PayrollInputLineListCreateView,
    PayrollPeriodCalculateView,
    PayrollPeriodCloseView,
    PayrollPeriodTableView,
    PayrollRunApproveView,
    PayrollRunDetailView,
    PayrollRunPublishView,
    PayrollRunReturnView,
    PayrollRunSubmitReviewView,
    PayrollWorkRecordApproveView,
    PayrollWorkRecordDetailView,
    PayrollWorkRecordListCreateView,
    PayrollWorkRecordReviseView,
)

app_name = "finance-payroll"

urlpatterns = [
    path(
        "payroll/admin/workspace/",
        PayrollAdminWorkspaceView.as_view(),
        name="admin-workspace",
    ),
    path(
        "payroll/admin/employees/",
        PayrollAdminEmployeeListView.as_view(),
        name="admin-employee-list",
    ),
    path(
        "payroll/admin/components/",
        PayrollAdminComponentListView.as_view(),
        name="admin-component-list",
    ),
    path(
        "payroll/admin/periods/",
        PayrollAdminPeriodListCreateView.as_view(),
        name="admin-period-list",
    ),
    path(
        "payroll/admin/periods/<int:pk>/",
        PayrollAdminPeriodDetailView.as_view(),
        name="admin-period-detail",
    ),
    path(
        "payroll/admin/periods/<int:pk>/calculate/",
        PayrollPeriodCalculateView.as_view(),
        name="admin-period-calculate",
    ),
    path(
        "payroll/admin/periods/<int:pk>/table/",
        PayrollPeriodTableView.as_view(),
        name="admin-period-table",
    ),
    path(
        "payroll/admin/periods/<int:pk>/attendance-work-records/",
        PayrollAttendanceWorkRecordsView.as_view(),
        name="admin-period-attendance-work-records",
    ),
    path(
        "payroll/admin/periods/<int:pk>/bulk-pay-rate/",
        PayrollBulkPayRateView.as_view(),
        name="admin-period-bulk-pay-rate",
    ),
    path(
        "payroll/admin/periods/<int:pk>/bulk-point-rate/",
        PayrollBulkPointRateView.as_view(),
        name="admin-period-bulk-point-rate",
    ),
    path(
        "payroll/admin/periods/<int:pk>/close/",
        PayrollPeriodCloseView.as_view(),
        name="admin-period-close",
    ),
    path(
        "payroll/admin/pay-rates/",
        EmployeePayRateListCreateView.as_view(),
        name="admin-pay-rate-list",
    ),
    path(
        "payroll/admin/pay-rates/<int:pk>/",
        EmployeePayRateDetailView.as_view(),
        name="admin-pay-rate-detail",
    ),
    path(
        "payroll/admin/pay-rates/<int:pk>/approve/",
        EmployeePayRateApproveView.as_view(),
        name="admin-pay-rate-approve",
    ),
    path(
        "payroll/admin/pay-rates/<int:pk>/revise/",
        EmployeePayRateReviseView.as_view(),
        name="admin-pay-rate-revise",
    ),
    path(
        "payroll/admin/work-records/",
        PayrollWorkRecordListCreateView.as_view(),
        name="admin-work-record-list",
    ),
    path(
        "payroll/admin/work-records/<int:pk>/",
        PayrollWorkRecordDetailView.as_view(),
        name="admin-work-record-detail",
    ),
    path(
        "payroll/admin/work-records/<int:pk>/approve/",
        PayrollWorkRecordApproveView.as_view(),
        name="admin-work-record-approve",
    ),
    path(
        "payroll/admin/work-records/<int:pk>/revise/",
        PayrollWorkRecordReviseView.as_view(),
        name="admin-work-record-revise",
    ),
    path(
        "payroll/admin/input-lines/",
        PayrollInputLineListCreateView.as_view(),
        name="admin-input-line-list",
    ),
    path(
        "payroll/admin/input-lines/<int:pk>/",
        PayrollInputLineDetailView.as_view(),
        name="admin-input-line-detail",
    ),
    path(
        "payroll/admin/input-lines/<int:pk>/approve/",
        PayrollInputLineApproveView.as_view(),
        name="admin-input-line-approve",
    ),
    path(
        "payroll/admin/runs/<int:pk>/",
        PayrollRunDetailView.as_view(),
        name="admin-run-detail",
    ),
    path(
        "payroll/admin/runs/<int:pk>/submit-review/",
        PayrollRunSubmitReviewView.as_view(),
        name="admin-run-submit-review",
    ),
    path(
        "payroll/admin/runs/<int:pk>/return/",
        PayrollRunReturnView.as_view(),
        name="admin-run-return",
    ),
    path(
        "payroll/admin/runs/<int:pk>/approve/",
        PayrollRunApproveView.as_view(),
        name="admin-run-approve",
    ),
    path(
        "payroll/admin/runs/<int:pk>/publish/",
        PayrollRunPublishView.as_view(),
        name="admin-run-publish",
    ),
    path(
        "payroll/me/work-records/",
        OwnPayrollWorkRecordView.as_view(),
        name="own-work-records",
    ),
    path(
        "payroll/me/statements/",
        OwnPayrollStatementListView.as_view(),
        name="own-statement-list",
    ),
    path(
        "payroll/me/statements/<uuid:public_id>/",
        OwnPayrollStatementDetailView.as_view(),
        name="own-statement-detail",
    ),
    path(
        "payroll/me/statements/<uuid:public_id>/acknowledge/",
        OwnPayrollStatementAcknowledgeView.as_view(),
        name="own-statement-acknowledge",
    ),
]
