# Generated by Django 5.2.4 on 2025-12-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_equipmenttransferlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrequest',
            name='estimated_cost',
        ),
    ]
