# Generated by Django 5.2.4 on 2025-12-10 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_remove_estimated_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='executor',
            field=models.ForeignKey(blank=True, help_text='Кто взял заявку в работу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executing_procurements', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Взято в работу'),
        ),
    ]
