# Generated by Django 5.2.4 on 2026-03-27 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_add_executor_and_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('department_head', 'Руководитель отдела'), ('finance_manager', 'Финансовый менеджер'), ('director', 'Генеральный директор')], max_length=20, unique=True, verbose_name='Роль')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_routes', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
            },
        ),
    ]
