# Generated by Django 5.2.4 on 2026-03-27 23:55

from django.db import migrations, models


def set_default_priorities(apps, schema_editor):
    Approval = apps.get_model('procurement', 'Approval')
    ApprovalRoute = apps.get_model('procurement', 'ApprovalRoute')

    priorities = {
        'department_head': 10,
        'finance_manager': 20,
        'director': 30,
    }

    for role, priority in priorities.items():
        Approval.objects.filter(role=role).update(priority=priority)
        ApprovalRoute.objects.filter(role=role).update(priority=priority)


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_add_approval_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['priority', 'created_at', 'id'], 'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласования'},
        ),
        migrations.AlterModelOptions(
            name='approvalroute',
            options={'ordering': ['priority', 'role', 'id'], 'verbose_name': 'Маршрут согласования', 'verbose_name_plural': 'Маршруты согласования'},
        ),
        migrations.AddField(
            model_name='approval',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Чем меньше число, тем раньше этап в цепочке согласования.', verbose_name='Приоритет'),
        ),
        migrations.RunPython(set_default_priorities, migrations.RunPython.noop),
    ]
