# Generated by Django 5.2.4 on 2026-03-28 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_route_roles_to_resolver_types(apps, schema_editor):
    ApprovalRoute = apps.get_model('procurement', 'ApprovalRoute')
    ApprovalRoute.objects.filter(role='department_head').update(
        resolver_type='department_head',
        employee=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_add_approval_priorities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalroute',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Маршрут согласования', 'verbose_name_plural': 'Маршруты согласования'},
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('request', 'priority')},
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='resolver_type',
            field=models.CharField(choices=[('department_head', 'Руководитель отдела'), ('fixed_employee', 'Конкретный сотрудник')], default='fixed_employee', max_length=20, verbose_name='Тип резолва'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='approvalroute',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_routes', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий'),
        ),
        migrations.AlterField(
            model_name='approvalroute',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Чем меньше число, тем раньше этап в цепочке согласования.', unique=True, verbose_name='Приоритет'),
        ),
        migrations.RunPython(
            migrate_route_roles_to_resolver_types,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='approvalroute',
            name='role',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='role',
        ),
    ]
