# Generated by Django 5.2.4 on 2026-03-28 00:21

from django.db import migrations, models


def populate_step_names(apps, schema_editor):
    Approval = apps.get_model('procurement', 'Approval')
    ApprovalRoute = apps.get_model('procurement', 'ApprovalRoute')

    default_names = {
        10: 'Руководитель отдела',
        20: 'Финансовый менеджер',
        30: 'Генеральный директор',
    }

    route_names = {
        route.priority: (route.name or default_names.get(route.priority, f'Этап {route.priority}'))
        for route in ApprovalRoute.objects.all()
    }

    for approval in Approval.objects.all():
        approval.step_name = route_names.get(
            approval.priority,
            default_names.get(approval.priority, f'Этап {approval.priority}'),
        )
        approval.save(update_fields=['step_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_replace_roles_with_priority_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='step_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название этапа'),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='name',
            field=models.CharField(blank=True, help_text='Необязательно. Если заполнено, будет показано в интерфейсе.', max_length=150, verbose_name='Название этапа'),
        ),
        migrations.RunPython(populate_step_names, migrations.RunPython.noop),
    ]
