# Generated by Django 5.2.4 on 2026-03-28 00:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_legacy_min_amounts(apps, schema_editor):
    ApprovalRoute = apps.get_model('procurement', 'ApprovalRoute')

    ApprovalRoute.objects.filter(
        priority=20,
        min_amount__isnull=True,
    ).update(min_amount=Decimal('10000.00'))
    ApprovalRoute.objects.filter(
        priority=30,
        min_amount__isnull=True,
    ).update(min_amount=Decimal('50000.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_add_step_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalroute',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто = этап обязателен для любой суммы. Иначе этап включается при сумме не меньше указанной.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Минимальная сумма заявки'),
        ),
        migrations.RunPython(
            backfill_legacy_min_amounts,
            migrations.RunPython.noop,
        ),
    ]
