# Generated by Codex on 2026-05-22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0052_employee_attendance_aliases"),
        ("procurement", "0009_approvalroute_min_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurementrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("waiting", "Ожидает"),
                    ("pending", "На согласовании"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                    ("in_progress", "В работе"),
                    ("completed", "Завершено"),
                    ("cancelled", "Отменено"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает обработки"),
                    ("partially_ordered", "Заказано частично"),
                    ("ordered", "Заказано"),
                    ("partially_received", "Прибыл частично"),
                    ("completed", "Выполнено"),
                    ("issues", "Выполнено с проблемами"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Статус исполнения",
            ),
        ),
        migrations.AddField(
            model_name="procurementrequest",
            name="processing_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Отдел, который должен обработать заявку",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_procurement_requests",
                to="employees.department",
                verbose_name="Отдел-исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="actual_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01"))
                ],
                verbose_name="Фактическая цена за единицу",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="execution_status",
            field=models.CharField(
                choices=[
                    ("pending", "Не выполнено"),
                    ("ordered", "Заказано"),
                    ("rejected", "Отказано"),
                    ("received", "Получено"),
                    ("completed_with_issue", "Выполнено с замечанием"),
                    ("edited", "Отредактировано"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="expected_delivery_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Ожидаемая дата поступления",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="executor_comment",
            field=models.TextField(
                blank=True,
                verbose_name="Комментарий исполнителя",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список ссылок на позицию",
                verbose_name="Ссылки",
            ),
        ),
    ]
