# Generated by Codex on 2026-05-26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_processing_department_and_execution_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurementitem",
            name="estimated_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01"))
                ],
                verbose_name="Цена за единицу",
            ),
        ),
        migrations.AlterField(
            model_name="procurementitem",
            name="execution_status",
            field=models.CharField(
                choices=[
                    ("pending", "Не выполнено"),
                    ("ordered", "Заказано"),
                    ("rejected", "Отказано"),
                    ("received", "Получено"),
                    ("completed_with_issue", "Выполнено с замечанием"),
                    ("edited", "Отредактировано"),
                    ("defective", "Брак / перезаказ"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="ordered_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сколько единиц заказал исполнитель",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Заказанное количество",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="received_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Сколько единиц фактически получено",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Полученное количество",
            ),
        ),
    ]
