# Generated by Codex on 2026-06-01

from django.db import migrations, models


def forwards(apps, schema_editor):
    ProcurementItem = apps.get_model("procurement", "ProcurementItem")
    for item in ProcurementItem.objects.all().iterator():
        if item.expected_delivery_date:
            item.expected_delivery_dates = [item.expected_delivery_date.isoformat()]
        else:
            item.expected_delivery_dates = []
        item.save(update_fields=["expected_delivery_dates"])


def backwards(apps, schema_editor):
    ProcurementItem = apps.get_model("procurement", "ProcurementItem")
    for item in ProcurementItem.objects.all().iterator():
        dates = item.expected_delivery_dates or []
        item.expected_delivery_date = dates[0] if dates else None
        item.save(update_fields=["expected_delivery_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_item_quantities_defective_optional_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementitem",
            name="expected_delivery_dates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список ожидаемых дат поступления в формате YYYY-MM-DD",
                verbose_name="Ожидаемые даты поступления",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="procurementitem",
            name="expected_delivery_date",
        ),
    ]
