# Generated by Codex on 2026-06-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0012_expected_delivery_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementRequestView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=True, verbose_name="Просмотрено"),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Просмотрено в",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_states",
                        to="procurement.procurementrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_request_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка просмотра заявки",
                "verbose_name_plural": "Отметки просмотра заявок",
            },
        ),
        migrations.AddConstraint(
            model_name="procurementrequestview",
            constraint=models.UniqueConstraint(
                fields=("request", "user"),
                name="unique_procurement_request_view_user",
            ),
        ),
    ]
