# Generated by Django 5.2.4 on 2026-07-17 07:34

import django.db.models.deletion
import procurement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_procurementsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=procurement.models.procurement_item_attachment_upload_to, verbose_name='Файл')),
                ('file_name', models.TextField(verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла')),
                ('mime_type', models.CharField(blank=True, max_length=255, verbose_name='MIME-тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procurement.procurementitem', verbose_name='Позиция')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_item_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение позиции закупки',
                'verbose_name_plural': 'Вложения позиций закупки',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
