# Generated by Django 5.2.4 on 2025-07-29 05:31

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_birth_date_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', users.models.EmployeeManager()),
            ],
        ),
    ]
