# Generated by Django 5.2.4 on 2025-07-28 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsubscriber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='botsubscriber',
            name='registration_token',
        ),
        migrations.RemoveField(
            model_name='botsubscriber',
            name='token_created',
        ),
        migrations.AddField(
            model_name='botsubscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отвязки'),
        ),
        migrations.AlterField(
            model_name='botsubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки'),
        ),
        migrations.AlterField(
            model_name='botsubscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
