# Generated by Django 5.2.4 on 2025-07-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_remove_botsubscriber_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsubscriber',
            name='subscribed_at',
        ),
        migrations.RemoveField(
            model_name='botsubscriber',
            name='unsubscribed_at',
        ),
    ]
