# Generated by Django 5.2.4 on 2025-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_botsubscriber_subscribed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscriber',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='WeChat ID'),
        ),
    ]
