# Generated by Django 5.2.4 on 2025-08-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-created_at'], 'permissions': [('publish_company_post', 'Can publish on main page'), ('publish_department_post', 'Can publish in department')], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
