# Generated by Django 5.2.4 on 2025-08-08 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employeedepartment_date_from_and_more'),
        ('feed', '0002_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-created_at'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feed/attachments/%Y/%m/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Для новостей отдела укажите отдел. Для других типов оставьте пустым.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='employees.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed/images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('company', 'Новость компании'), ('department', 'Новость отдела'), ('employee', 'Публикация сотрудника')], max_length=20, verbose_name='Тип публикации'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='feed_commen_created_a85775_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['type', 'created_at'], name='feed_post_type_b00891_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['pinned', 'created_at'], name='feed_post_pinned_e86c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='feed_post_created_ddd8c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('type', 'department')), models.Q(('type', 'department'), _negated=True), _connector='OR'), name='post_department_required_when_type_is_department'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'department'), models.Q(('department__isnull', True), ('type__in', ['company', 'employee'])), _connector='OR'), name='post_department_null_when_type_not_department'),
        ),
    ]
