# Generated by Django 5.2.4 on 2025-10-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_ldapsyncstate'),
        ('feed', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Для новостей отдела укажите отдел. Для других типов оставьте пустым.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='employees.department', verbose_name='Отдел'),
        ),
    ]
