# Generated by Django 5.2.4 on 2026-03-11 19:33

from django.db import migrations


def migrate_comments_forward(apps, schema_editor):
    """Миграция feed.Comment → Communications.Message (SQL с вложениями)"""
    
    # 1. Создаем чаты для постов с комментариями
    schema_editor.execute("""
        INSERT INTO communications_chat (
            type, name, created_by_id, can_reply, flags,
            context_content_type_id, context_object_id
        )
        SELECT DISTINCT
            'comments',
            'Комментарии: ' || substr(p.title, 1, 50),
            NULL::bigint,
            TRUE,
            '{"allow_replies": true, "allow_reactions": true, "allow_attachments": true, "allow_editing": true}'::jsonb,
            (SELECT id FROM django_content_type WHERE app_label='feed' AND model='post'),
            c.post_id
        FROM feed_comment c
        JOIN feed_post p ON p.id = c.post_id
        WHERE NOT EXISTS (
            SELECT 1 FROM communications_chat cc
            WHERE cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='feed' AND model='post')
            AND cc.context_object_id = c.post_id
        )
    """)
    
    # 2. Переносим комментарии
    schema_editor.execute("""
        INSERT INTO communications_message (
            chat_id, author_id, content, created_at,
            is_system, has_attachments,
            is_deleted, is_edited, is_pinned, is_forwarded, is_cross_chat,
            system_metadata
        )
        SELECT 
            cc.id,
            c.author_id,
            c.text,
            c.created_at,
            FALSE,
            CASE WHEN (c.image != '' OR c.attachment != '') THEN TRUE ELSE FALSE END,
            FALSE, FALSE, FALSE, FALSE, FALSE,
            jsonb_build_object(
                'legacy_comment_id', c.id,
                'legacy_model', 'feed.Comment'
            )
        FROM feed_comment c
        JOIN communications_chat cc ON (
            cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='feed' AND model='post')
            AND cc.context_object_id = c.post_id
        )
        WHERE NOT EXISTS (
            SELECT 1 FROM communications_message m
            WHERE m.chat_id = cc.id
            AND m.author_id = c.author_id
            AND m.created_at = c.created_at
        )
    """)
    
    # 3. Переносим вложения (images)
    schema_editor.execute("""
        INSERT INTO communications_messageattachment (
            message_id, file, file_type, file_name, file_size, uploaded_at
        )
        SELECT 
            m.id,
            c.image,
            'image',
            substr(c.image, instr(c.image, '/') + 1),
            0,
            c.created_at
        FROM feed_comment c
        JOIN communications_chat cc ON (
            cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='feed' AND model='post')
            AND cc.context_object_id = c.post_id
        )
        JOIN communications_message m ON (
            m.chat_id = cc.id
            AND m.author_id = c.author_id
            AND m.created_at = c.created_at
        )
        WHERE c.image != '' AND c.image IS NOT NULL
    """)
    
    # 4. Переносим вложения (attachments)
    schema_editor.execute("""
        INSERT INTO communications_messageattachment (
            message_id, file, file_type, file_name, file_size, uploaded_at
        )
        SELECT 
            m.id,
            c.attachment,
            'file',
            substr(c.attachment, instr(c.attachment, '/') + 1),
            0,
            c.created_at
        FROM feed_comment c
        JOIN communications_chat cc ON (
            cc.type = 'comments'
            AND cc.context_content_type_id = (SELECT id FROM django_content_type WHERE app_label='feed' AND model='post')
            AND cc.context_object_id = c.post_id
        )
        JOIN communications_message m ON (
            m.chat_id = cc.id
            AND m.author_id = c.author_id
            AND m.created_at = c.created_at
        )
        WHERE c.attachment != '' AND c.attachment IS NOT NULL
    """)


def migrate_comments_backward(apps, schema_editor):
    """Откат - удаляем чаты комментариев для постов"""
    schema_editor.execute("""
        DELETE FROM communications_chat
        WHERE type = 'comments'
        AND context_content_type_id = (
            SELECT id FROM django_content_type 
            WHERE app_label='feed' AND model='post'
        )
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_department'),
        ('communications', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_comments_forward,
            migrate_comments_backward
        ),
    ]
