# Generated by Django 5.2.4 on 2026-03-11 19:33

from django.db import migrations
from django.utils import timezone


def migrate_comments_forward(apps, schema_editor):
    """Миграция feed.Comment → Communications.Message (ORM)"""

    Chat = apps.get_model('communications', 'Chat')
    Message = apps.get_model('communications', 'Message')
    MessageAttachment = apps.get_model('communications', 'MessageAttachment')
    Comment = apps.get_model('feed', 'Comment')
    Post = apps.get_model('feed', 'Post')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        post_ct = ContentType.objects.get(app_label='feed', model='post')
    except ContentType.DoesNotExist:
        return  # Если ContentType не найден, пропускаем миграцию

    # 1. Создаем чаты для постов с комментариями
    post_ids_with_comments = Comment.objects.values_list('post_id', flat=True).distinct()

    for post_id in post_ids_with_comments:
        # Проверяем, не создан ли уже чат
        if Chat.objects.filter(
            type='comments',
            context_content_type=post_ct,
            context_object_id=post_id
        ).exists():
            continue

        try:
            post = Post.objects.get(id=post_id)
            chat_name = f"Комментарии: {post.title[:50]}" if hasattr(post, 'title') and post.title else "Комментарии"
        except Post.DoesNotExist:
            chat_name = "Комментарии"

        Chat.objects.create(
            type='comments',
            name=chat_name,
            description='',
            avatar=None,
            created_by=None,
            can_reply=True,
            flags={'allow_replies': True, 'allow_reactions': True, 'allow_attachments': True, 'allow_editing': True},
            context_content_type=post_ct,
            context_object_id=post_id,
            created_at=timezone.now(),
            is_main=False,
            is_blocked=False,
            include_all_users=False,
            extra_data={}
        )

    # 2. Переносим комментарии
    for comment in Comment.objects.select_related('author', 'post').all():
        try:
            chat = Chat.objects.get(
                type='comments',
                context_content_type=post_ct,
                context_object_id=comment.post_id
            )
        except Chat.DoesNotExist:
            continue

        # Проверяем, не перенесен ли уже комментарий
        if Message.objects.filter(
            chat=chat,
            author=comment.author,
            created_at=comment.created_at
        ).exists():
            continue

        # Проверяем наличие вложений
        has_image = bool(comment.image and str(comment.image).strip())
        has_attachment = bool(comment.attachment and str(comment.attachment).strip())
        has_attachments = has_image or has_attachment

        message = Message.objects.create(
            chat=chat,
            author=comment.author,
            content=comment.text or '',
            created_at=comment.created_at,
            is_system=False,
            has_attachments=has_attachments,
            is_deleted=False,
            is_edited=False,
            is_pinned=False,
            is_forwarded=False,
            is_cross_chat=False,
            system_type='',
            system_metadata={
                'legacy_comment_id': comment.id,
                'legacy_model': 'feed.Comment'
            }
        )

        # 3. Переносим вложения
        if has_image:
            file_name = str(comment.image).split('/')[-1] if '/' in str(comment.image) else str(comment.image)
            MessageAttachment.objects.create(
                message=message,
                file=comment.image,
                file_type='image',
                file_name=file_name,
                file_size=0,
                uploaded_at=comment.created_at
            )

        if has_attachment:
            file_name = str(comment.attachment).split('/')[-1] if '/' in str(comment.attachment) else str(comment.attachment)
            MessageAttachment.objects.create(
                message=message,
                file=comment.attachment,
                file_type='file',
                file_name=file_name,
                file_size=0,
                uploaded_at=comment.created_at
            )


def migrate_comments_backward(apps, schema_editor):
    """Откат - удаляем чаты комментариев для постов"""
    Chat = apps.get_model('communications', 'Chat')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        post_ct = ContentType.objects.get(app_label='feed', model='post')
        Chat.objects.filter(
            type='comments',
            context_content_type=post_ct
        ).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_department'),
        ('communications', '0037_remove_department_type'),  # Зафиксировали конкретную версию
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_comments_forward,
            migrate_comments_backward
        ),
    ]
