# Generated by Django 5.2.4 on 2026-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_split_post_pins_by_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, editable=False, verbose_name='Закреплено (legacy)'),
        ),
    ]
